nixd: nixf::TextEdit Class Reference
nixf::TextEdit Class Reference
#include <Diagnostic.h>
Public Member Functions
TextEdit (LexerCursorRange OldRange, std::string NewText)
bool isReplace () const
bool isRemoval () const
bool isInsertion () const
LexerCursorRange oldRange () const
std::string_view newText () const
Static Public Member Functions
static TextEdit mkInsertion (LexerCursor P, std::string NewText)
static TextEdit mkRemoval (LexerCursorRange RemovingRange)
Detailed Description
Remove the text at OldRange, and replace it as NewText Special cases:
Insertions: special OldRange that Begin == End.
Removals: empty NewText.
Definition at line 25 of file Diagnostic.h.
Constructor & Destructor Documentation
TextEdit()
nixf::TextEdit::TextEdit (LexerCursorRange OldRange, std::string NewText) inline
Definition at line 30 of file Diagnostic.h.
Referenced by mkInsertion(), and mkRemoval().
Member Function Documentation
isInsertion()
bool nixf::TextEdit::isInsertion () const inline nodiscard
Definition at line 49 of file Diagnostic.h.
Referenced by isReplace().
isRemoval()
bool nixf::TextEdit::isRemoval () const inline nodiscard
Definition at line 47 of file Diagnostic.h.
Referenced by isReplace().
isReplace()
bool nixf::TextEdit::isReplace () const inline nodiscard
Definition at line 43 of file Diagnostic.h.
References isInsertion(), and isRemoval().
mkInsertion()
static TextEdit nixf::TextEdit::mkInsertion (LexerCursor P, std::string NewText) inline static
Definition at line 35 of file Diagnostic.h.
References TextEdit().
Referenced by nixf::Sema::checkFormalEllipsis(), nixf::Sema::checkFormalSep(), nixf::detail::diagNullExpr(), nixf::Parser::parseAttrPath(), nixf::Parser::parseBinding(), nixf::Parser::parseExprIf(), nixf::Parser::parseExprSelect(), nixf::Parser::parseExprSimple(), and nixf::Parser::parseLambdaArg().
mkRemoval()
static TextEdit nixf::TextEdit::mkRemoval (LexerCursorRange RemovingRange) inline static
Definition at line 39 of file Diagnostic.h.
References TextEdit().
Referenced by nixf::Sema::checkFormalEmpty(), nixf::Sema::lowerInheritName(), nixf::Parser::parseAttrPath(), nixf::Parser::parseExprAssert(), nixf::Parser::parseExprIf(), nixf::Parser::parseExprParen(), nixf::Parser::parseExprSelect(), nixf::Parser::parseInherit(), nixf::Parser::parseLambdaArg(), and nixf::Sema::removeFormal().
newText()
std::string_view nixf::TextEdit::newText () const inline nodiscard
Definition at line 54 of file Diagnostic.h.
oldRange()
LexerCursorRange nixf::TextEdit::oldRange () const inline nodiscard
Definition at line 53 of file Diagnostic.h.
The documentation for this class was generated from the following file:
Diagnostic.h