nixd: nixf::ParentMapAnalysis Class Reference
nixf::ParentMapAnalysis Class Reference
#include <ParentMap.h>
Public Member Functions
void runOnAST (const Node &Root)
const Node * query (const Node &N) const
const Node * upExpr (const Node &N) const
Search up until the node becomes a concrete expression. a ^<--— ID -> ExprVar.
const Node * upTo (const Node &N, Node::NodeKind Kind) const
Search up until some kind of node is found.
bool isRoot (const Node &N) const
Static Public Member Functions
static bool isRoot (const Node *Up, const Node &N)
Detailed Description
Definition at line 15 of file ParentMap.h.
Member Function Documentation
isRoot() [1/2]
bool nixf::ParentMapAnalysis::isRoot (const Node & N) const nodiscard
Definition at line 46 of file ParentMap.cpp.
References isRoot(), and query().
isRoot() [2/2]
bool nixf::ParentMapAnalysis::isRoot (const Node * Up, const Node & N) static
Definition at line 42 of file ParentMap.cpp.
Referenced by isRoot(), nixd::upEnv(), upExpr(), and upTo().
query()
const Node * ParentMapAnalysis::query (const Node & N) const nodiscard
Definition at line 13 of file ParentMap.cpp.
Referenced by isRoot(), nixd::idioms::mkVarSelector(), nixd::upEnv(), upExpr(), and upTo().
runOnAST()
void ParentMapAnalysis::runOnAST (const Node & Root)
Definition at line 37 of file ParentMap.cpp.
upExpr()
const Node * ParentMapAnalysis::upExpr (const Node & N) const nodiscard
Search up until the node becomes a concrete expression. a ^<--— ID -> ExprVar.
Definition at line 17 of file ParentMap.cpp.
References nixf::Expr::isExpr(), isRoot(), nixf::Node::kind(), query(), and upExpr().
Referenced by upExpr().
upTo()
const Node * ParentMapAnalysis::upTo (const Node & N, Node::NodeKind Kind) const nodiscard
Search up until some kind of node is found.
Definition at line 27 of file ParentMap.cpp.
References isRoot(), nixf::Node::kind(), query(), and upTo().
Referenced by nixd::findAttrPath(), and upTo().
The documentation for this class was generated from the following files:
ParentMap.h
ParentMap.cpp