nixd: nixd::OwnedEvalClient Class Reference
nixd::OwnedEvalClient Class Reference
#include <EvalClient.h>
Public Member Functions
OwnedEvalClient (std::unique_ptr< lspserver::InboundPort > In, std::unique_ptr< lspserver::OutboundPort > Out, std::unique_ptr< util::PipedProc > Proc, std::unique_ptr< llvm::raw_fd_ostream > Stream)
util::PipedProc & proc ()
~OwnedEvalClient () override
Public Member Functions inherited from nixd::EvalClient
EvalClient (std::unique_ptr< lspserver::InboundPort > In, std::unique_ptr< lspserver::OutboundPort > Out)
void onReady (const int &Flags)
bool ready ()
Public Member Functions inherited from lspserver::LSPServer
LSPServer (std::unique_ptr< InboundPort > In, std::unique_ptr< OutboundPort > Out)
void closeInbound ()
Close the inbound port.
void run ()
void switchStreamStyle (JSONStreamStyle Style)
Public Member Functions inherited from lspserver::MessageHandler
virtual ~MessageHandler ()=default
Static Public Member Functions
static std::unique_ptr< OwnedEvalClient > create (int &Fail)
Additional Inherited Members
Public Attributes inherited from nixd::EvalClient
llvm::unique_function< void(const rpc::RegisterBCParams &)> RegisterBC
llvm::unique_function< void(const rpc::ExprValueParams &, lspserver::Callback< rpc::ExprValueResponse >)> ExprValue
Protected Member Functions inherited from lspserver::LSPServer
template<class T>
llvm::unique_function< void(const T &)> mkOutNotifiction (llvm::StringRef Method, OutboundPort *O=nullptr)
template<class ParamTy, class ResponseTy>
llvm::unique_function< void(const ParamTy &, Callback< ResponseTy >)> mkOutMethod (llvm::StringRef Method, OutboundPort *O=nullptr)
Protected Attributes inherited from lspserver::LSPServer
HandlerRegistry Registry
Detailed Description
Definition at line 36 of file EvalClient.h.
Constructor & Destructor Documentation
OwnedEvalClient()
nixd::OwnedEvalClient::OwnedEvalClient (std::unique_ptr< lspserver::InboundPort > In, std::unique_ptr< lspserver::OutboundPort > Out, std::unique_ptr< util::PipedProc > Proc, std::unique_ptr< llvm::raw_fd_ostream > Stream) inline
Definition at line 43 of file EvalClient.h.
References nixd::EvalClient::EvalClient(), and lspserver::LSPServer::run().
~OwnedEvalClient()
nixd::OwnedEvalClient::~OwnedEvalClient () inline override
Definition at line 55 of file EvalClient.h.
References lspserver::LSPServer::closeInbound().
Member Function Documentation
create()
static std::unique_ptr< OwnedEvalClient > nixd::OwnedEvalClient::create (int & Fail) static
Lanch nix-node-eval, with properly handled file descriptors. System-wide errno will be written into "Fail" variable and thus cannot be discarded.
proc()
util::PipedProc & nixd::OwnedEvalClient::proc () inline
Definition at line 53 of file EvalClient.h.
The documentation for this class was generated from the following file:
EvalClient.h