nixd: nixt::ASTDeserializer Class Reference
nixt::ASTDeserializer Class Reference
#include <ASTReader.h>
Public Member Functions
ASTDeserializer (DeserializeContext &Ctx, PtrPool< nix::Expr > &Pool)
nix::Expr * eatHookable (std::string_view &Data, ValueMap &VMap, EnvMap &EMap)
nix::Symbol eatSymbol (std::string_view &Data)
nix::ExprInt eatExprInt (std::string_view &Data)
Detailed Description
Definition at line 13 of file ASTReader.h.
Constructor & Destructor Documentation
ASTDeserializer()
nixt::ASTDeserializer::ASTDeserializer (DeserializeContext & Ctx, PtrPool< nix::Expr > & Pool) inline
Definition at line 20 of file ASTReader.h.
Member Function Documentation
eatExprInt()
nix::ExprInt nixt::ASTDeserializer::eatExprInt (std::string_view & Data)
Definition at line 38 of file ASTReader.cpp.
Referenced by eatHookable().
eatHookable()
nix::Expr * nixt::ASTDeserializer::eatHookable (std::string_view & Data, ValueMap & VMap, EnvMap & EMap)
Definition at line 18 of file ASTReader.cpp.
References eatExprInt(), nixbc::EK_Int, and nixt::PtrPool< T >::record().
Referenced by nixt::deserializeHookable().
eatSymbol()
nix::Symbol nixt::ASTDeserializer::eatSymbol (std::string_view & Data)
Definition at line 34 of file ASTReader.cpp.
References nixt::DeserializeContext::STable.
The documentation for this class was generated from the following files:
ASTReader.h
ASTReader.cpp