nixd: nixf::LexerCursorRange Class Reference
nixf::LexerCursorRange Class Reference
#include <Range.h>
Public Member Functions
LexerCursorRange ()=default
LexerCursorRange (LexerCursor LCur, LexerCursor RCur)
LexerCursorRange (LexerCursor Pos)
LexerCursor lCur () const
LexerCursor rCur () const
bool contains (const LexerCursorRange &Pos) const
PositionRange range () const
Detailed Description
Definition at line 105 of file Range.h.
Constructor & Destructor Documentation
LexerCursorRange() [1/3]
nixf::LexerCursorRange::LexerCursorRange () default
Referenced by contains().
LexerCursorRange() [2/3]
nixf::LexerCursorRange::LexerCursorRange (LexerCursor LCur, LexerCursor RCur) inline
Definition at line 112 of file Range.h.
LexerCursorRange() [3/3]
nixf::LexerCursorRange::LexerCursorRange (LexerCursor Pos) inline explicit
Definition at line 114 of file Range.h.
Member Function Documentation
contains()
bool nixf::LexerCursorRange::contains (const LexerCursorRange & Pos) const inline nodiscard
Definition at line 119 of file Range.h.
References nixf::PositionRange::contains(), LexerCursorRange(), and range().
lCur()
LexerCursor nixf::LexerCursorRange::lCur () const inline nodiscard
Definition at line 116 of file Range.h.
Referenced by nixd::toLSPRange().
range()
PositionRange nixf::LexerCursorRange::range () const inline nodiscard
Definition at line 123 of file Range.h.
Referenced by contains().
rCur()
LexerCursor nixf::LexerCursorRange::rCur () const inline nodiscard
Definition at line 117 of file Range.h.
Referenced by nixd::toLSPRange().
The documentation for this class was generated from the following file:
Range.h