nixd: nixf::EnvNode Class Reference
nixf::EnvNode Class Reference
A set of variable definitions, which may inherit parent environment.
#include <VariableLookup.h>
Public Types
using DefMap = std::map<std::string, std::shared_ptr<Definition>>
Public Member Functions
EnvNode (std::shared_ptr< EnvNode > Parent, DefMap Defs, const Node *Syntax)
EnvNode * parent () const
const Node * syntax () const
Where this node comes from.
bool isWith () const
const DefMap & defs () const
bool isLive () const
Detailed Description
A set of variable definitions, which may inherit parent environment.
Definition at line 83 of file VariableLookup.h.
Member Typedef Documentation
DefMap
using nixf::EnvNode::DefMap = std::map<std::string, std::shared_ptr<Definition>>
Definition at line 85 of file VariableLookup.h.
Constructor & Destructor Documentation
EnvNode()
nixf::EnvNode::EnvNode (std::shared_ptr< EnvNode > Parent, DefMap Defs, const Node * Syntax) inline
Definition at line 95 of file VariableLookup.h.
Referenced by parent().
Member Function Documentation
defs()
const DefMap & nixf::EnvNode::defs () const inline nodiscard
Definition at line 107 of file VariableLookup.h.
isLive()
bool EnvNode::isLive () const nodiscard
Definition at line 35 of file VariableLookup.cpp.
isWith()
bool nixf::EnvNode::isWith () const inline nodiscard
Definition at line 103 of file VariableLookup.h.
Referenced by nixd::havePackageScope().
parent()
EnvNode * nixf::EnvNode::parent () const inline nodiscard
Definition at line 98 of file VariableLookup.h.
References EnvNode().
Referenced by nixd::havePackageScope().
syntax()
const Node * nixf::EnvNode::syntax () const inline nodiscard
Where this node comes from.
Definition at line 101 of file VariableLookup.h.
Referenced by nixd::havePackageScope().
The documentation for this class was generated from the following files:
VariableLookup.h
VariableLookup.cpp