nixd: lspserver::OutboundPort Class Reference
lspserver::OutboundPort Class Reference
#include <Connection.h>
Public Member Functions
OutboundPort (bool Pretty=false)
OutboundPort (llvm::raw_ostream &Outs, bool Pretty=false)
void notify (llvm::StringRef Method, llvm::json::Value Params)
void call (llvm::StringRef Method, llvm::json::Value Params, llvm::json::Value ID)
void reply (llvm::json::Value ID, llvm::Expected< llvm::json::Value > Result)
void sendMessage (llvm::json::Value Message)
Detailed Description
Definition at line 70 of file Connection.h.
Constructor & Destructor Documentation
OutboundPort() [1/2]
lspserver::OutboundPort::OutboundPort (bool Pretty = false) inline explicit
Definition at line 81 of file Connection.h.
OutboundPort() [2/2]
lspserver::OutboundPort::OutboundPort (llvm::raw_ostream & Outs, bool Pretty = false) inline
Definition at line 83 of file Connection.h.
Member Function Documentation
call()
void lspserver::OutboundPort::call (llvm::StringRef Method, llvm::json::Value Params, llvm::json::Value ID)
Definition at line 87 of file Connection.cpp.
References lspserver::Method, and sendMessage().
notify()
void lspserver::OutboundPort::notify (llvm::StringRef Method, llvm::json::Value Params)
Definition at line 80 of file Connection.cpp.
References lspserver::Method, and sendMessage().
Referenced by lspserver::LSPServer::mkOutNotifiction().
reply()
void lspserver::OutboundPort::reply (llvm::json::Value ID, llvm::Expected< llvm::json::Value > Result)
Definition at line 96 of file Connection.cpp.
References sendMessage().
sendMessage()
void lspserver::OutboundPort::sendMessage (llvm::json::Value Message)
Definition at line 113 of file Connection.cpp.
References lspserver::vlog().
Referenced by call(), notify(), and reply().
The documentation for this class was generated from the following files:
Connection.h
Connection.cpp