nixd: nixf::Parser Class Reference
nixf::Parser Class Reference
#include <Parser.h>
Public Types
enum ParserState { PS_Expr , PS_String , PS_IndString , PS_Path }
Public Member Functions
Parser (std::string_view Src, std::vector< Diagnostic > &Diags)
std::shared_ptr< Interpolation > parseInterpolation ()
Parse interpolations.
std::shared_ptr< Expr > parseExprPath ()
Parse paths.
std::shared_ptr< InterpolatedParts > parseStringParts ()
std::shared_ptr< ExprString > parseString (bool IsIndented)
std::shared_ptr< ExprParen > parseExprParen ()
std::shared_ptr< AttrName > parseAttrName ()
std::shared_ptr< AttrPath > parseAttrPath ()
std::shared_ptr< Binding > parseBinding ()
std::shared_ptr< Inherit > parseInherit ()
std::shared_ptr< Binds > parseBinds ()
std::shared_ptr< ExprAttrs > parseExprAttrs ()
std::shared_ptr< Expr > parseExprSimple ()
std::shared_ptr< Expr > parseExprSelect ()
std::shared_ptr< Expr > parseExprApp (int Limit=INT_MAX)
std::shared_ptr< ExprList > parseExprList ()
std::shared_ptr< Formal > parseFormal ()
std::shared_ptr< Formals > parseFormals ()
std::shared_ptr< LambdaArg > parseLambdaArg ()
std::shared_ptr< ExprLambda > parseExprLambda ()
std::shared_ptr< Expr > parseExpr ()
std::shared_ptr< Expr > parseExprOp ()
Parse binary/unary operators.
std::shared_ptr< ExprIf > parseExprIf ()
std::shared_ptr< ExprAssert > parseExprAssert ()
std::shared_ptr< ExprLet > parseExprLet ()
std::shared_ptr< ExprWith > parseExprWith ()
std::shared_ptr< Expr > parse ()
Detailed Description
Definition at line 31 of file src/Parse/Parser.h.
Member Enumeration Documentation
ParserState
enum nixf::Parser::ParserState
Enumerator
PS_Expr
PS_String
PS_IndString
PS_Path
Definition at line 33 of file src/Parse/Parser.h.
Constructor & Destructor Documentation
Parser()
nixf::Parser::Parser (std::string_view Src, std::vector< Diagnostic > & Diags) inline
Definition at line 153 of file src/Parse/Parser.h.
References PS_Expr.
Member Function Documentation
parse()
std::shared_ptr< Expr > nixf::Parser::parse () inline
Definition at line 336 of file src/Parse/Parser.h.
References parseExpr().
Referenced by nixf::parse().
parseAttrName()
std::shared_ptr< AttrName > nixf::Parser::parseAttrName ()
attrname : ID
         | string
         | interpolation
Definition at line 7 of file ParseAttrs.cpp.
References nixf::Token::kind(), parseInterpolation(), and parseString().
Referenced by parseAttrPath(), and parseInherit().
parseAttrPath()
std::shared_ptr< AttrPath > nixf::Parser::parseAttrPath ()
attrpath : attrname ('.' attrname)*
Definition at line 31 of file ParseAttrs.cpp.
References nixf::Fix::edit(), nixf::Diagnostic::fix(), nixf::Token::kind(), nixf::TextEdit::mkInsertion(), nixf::TextEdit::mkRemoval(), and parseAttrName().
Referenced by parseBinding(), and parseExprSelect().
parseBinding()
std::shared_ptr< Binding > nixf::Parser::parseBinding ()
binding : attrpath '=' expr ';'
Definition at line 60 of file ParseAttrs.cpp.
References nixf::detail::diagNullExpr(), nixf::Fix::edit(), nixf::Diagnostic::fix(), nixf::Token::kind(), nixf::TextEdit::mkInsertion(), parseAttrPath(), parseExpr(), and nixf::tok::spelling().
Referenced by parseBinds().
parseBinds()
std::shared_ptr< Binds > nixf::Parser::parseBinds ()
binds : (binding | inherit)*
Definition at line 134 of file ParseAttrs.cpp.
References nixf::Token::lCur(), parseBinding(), and parseInherit().
Referenced by parseExprAttrs(), and parseExprLet().
parseExpr()
std::shared_ptr< Expr > nixf::Parser::parseExpr ()
Definition at line 74 of file ParseExpr.cpp.
References parseExprAssert(), parseExprIf(), parseExprLambda(), parseExprLet(), parseExprOp(), and parseExprWith().
Referenced by parse(), parseBinding(), parseExprAssert(), parseExprIf(), parseExprLambda(), parseExprLet(), parseExprParen(), parseExprWith(), parseFormal(), parseInherit(), and parseInterpolation().
parseExprApp()
std::shared_ptr< Expr > nixf::Parser::parseExprApp (int Limit = INT_MAX)
expr_app : expr_app expr_select
         | expr_select
Consume at most Limit number of expr_select as arguments e.g. Fn A1 A2 A3 with Limit = 2 will be parsed as ((Fn A1 A2) A3)
Definition at line 53 of file ParseExpr.cpp.
References nixf::LexerCursorRange::lCur(), and parseExprSelect().
parseExprAssert()
std::shared_ptr< ExprAssert > nixf::Parser::parseExprAssert ()
expr_assert : 'assert' expr ';' expr
Definition at line 195 of file ParseExpr.cpp.
References nixf::detail::diagNullExpr(), nixf::Fix::edit(), nixf::Diagnostic::fix(), nixf::Token::kind(), nixf::TextEdit::mkRemoval(), nixf::Diagnostic::note(), parseExpr(), nixf::Token::range(), and nixf::tok::spelling().
Referenced by parseExpr().
parseExprAttrs()
std::shared_ptr< ExprAttrs > nixf::Parser::parseExprAttrs ()
attrset_expr : REC? '{' binds '}'
Note: peek tok_kw_rec or tok_l_curly before calling this function.
Definition at line 167 of file ParseAttrs.cpp.
References nixf::Token::kind(), nixf::Token::lCur(), nixf::Sema::onExprAttrs(), parseBinds(), nixf::Token::range(), and nixf::tok::spelling().
Referenced by parseExprSimple().
parseExprIf()
std::shared_ptr< ExprIf > nixf::Parser::parseExprIf ()
expr_if : 'if' expr 'then' expr 'else' expr
Definition at line 128 of file ParseExpr.cpp.
References nixf::detail::diagNullExpr(), nixf::Fix::edit(), nixf::Diagnostic::fix(), nixf::Token::kind(), nixf::TextEdit::mkInsertion(), nixf::TextEdit::mkRemoval(), nixf::Diagnostic::note(), parseExpr(), nixf::Token::range(), nixf::Token::rCur(), and nixf::tok::spelling().
Referenced by parseExpr().
parseExprLambda()
std::shared_ptr< ExprLambda > nixf::Parser::parseExprLambda ()
expr_lambda : lambda_arg ':' expr
Definition at line 134 of file ParseLambda.cpp.
References nixf::detail::diagNullExpr(), parseExpr(), and parseLambdaArg().
Referenced by parseExpr().
parseExprLet()
std::shared_ptr< ExprLet > nixf::Parser::parseExprLet ()
epxr_let : 'let' binds 'in' expr
Definition at line 238 of file ParseExpr.cpp.
References nixf::detail::diagNullExpr(), nixf::Token::kind(), parseBinds(), parseExpr(), and nixf::Token::range().
Referenced by parseExpr().
parseExprList()
std::shared_ptr< ExprList > nixf::Parser::parseExprList ()
expr_list : '[' expr_select* ']'
Definition at line 35 of file ParseSimple.cpp.
References nixf::Token::kind(), nixf::Token::lCur(), parseExprSelect(), nixf::Token::range(), and nixf::tok::spelling().
Referenced by parseExprSimple().
parseExprOp()
std::shared_ptr< Expr > nixf::Parser::parseExprOp () inline
Parse binary/unary operators.
expr_op : '!' expr_op
        | '-' expr_op
        | expr_op BINARY_OP expr_op
        | expr_app
%right ->
%left ||
%left &&
%nonassoc == !=
%nonassoc < > <= >=
%right //
%left NOT
%left + -
%left * /
%right ++
%nonassoc '?'
%nonassoc NEGATE
Definition at line 314 of file src/Parse/Parser.h.
Referenced by parseExpr().
parseExprParen()
std::shared_ptr< ExprParen > nixf::Parser::parseExprParen ()
'(' expr ')'
Definition at line 9 of file ParseSimple.cpp.
References nixf::detail::diagNullExpr(), nixf::Token::kind(), nixf::Token::lCur(), parseExpr(), nixf::Token::range(), and nixf::tok::spelling().
Referenced by parseExprSimple().
parseExprPath()
std::shared_ptr< Expr > nixf::Parser::parseExprPath ()
Parse paths.
 path : path_fragment (path_fragment)*  path_end
Context     PS_Expr       PS_Path        PS_Path
The first token, path_fragment is lexed in PS_Expr context, then switch in "PS_Path" context. The ending token "path_end" shall be poped with context switching.
Definition at line 30 of file ParseStrings.cpp.
References nixf::Token::kind(), nixf::Token::lCur(), parseInterpolation(), PS_Path, nixf::Token::rCur(), and nixf::Token::view().
Referenced by parseExprSimple().
parseExprSelect()
std::shared_ptr< Expr > nixf::Parser::parseExprSelect ()
expr_select : expr_simple '.' attrpath
            | expr_simple '.' attrpath 'or' expr_select
            | expr_simple 'or' <-- special "apply", 'or' is argument
            | expr_simple
Definition at line 7 of file ParseExpr.cpp.
References nixf::detail::diagNullExpr(), nixf::Fix::edit(), nixf::Diagnostic::fix(), nixf::Token::kind(), nixf::Node::lCur(), nixf::TextEdit::mkInsertion(), nixf::TextEdit::mkRemoval(), parseAttrPath(), parseExprSelect(), parseExprSimple(), nixf::Token::range(), and nixf::Token::rCur().
Referenced by parseExprApp(), parseExprList(), and parseExprSelect().
parseExprSimple()
std::shared_ptr< Expr > nixf::Parser::parseExprSimple ()
expr_simple :  INT
            | ID
            | FLOAT
            | string
            | indented_string
            | path
            | hpath
            | uri
            | '(' expr ')'
            | legacy_let
            | attrset_expr
            | list
Definition at line 61 of file ParseSimple.cpp.
References nixf::Token::kind(), parseExprAttrs(), parseExprList(), parseExprParen(), parseExprPath(), parseString(), nixf::Token::range(), and nixf::Token::view().
Referenced by parseExprSelect().
parseExprWith()
std::shared_ptr< ExprWith > nixf::Parser::parseExprWith ()
expr_with :  'with' expr ';' expr
Definition at line 276 of file ParseExpr.cpp.
References nixf::detail::diagNullExpr(), nixf::Token::kind(), nixf::Diagnostic::note(), parseExpr(), nixf::Token::range(), and nixf::tok::spelling().
Referenced by parseExpr().
parseFormal()
std::shared_ptr< Formal > nixf::Parser::parseFormal ()
formal : ,? ID
       | ,? ID '?' expr
       | ,? ...
Definition at line 7 of file ParseLambda.cpp.
References nixf::detail::diagNullExpr(), nixf::Token::kind(), and parseExpr().
Referenced by parseFormals().
parseFormals()
std::shared_ptr< Formals > nixf::Parser::parseFormals ()
formals : '{' formal* '}'
Definition at line 51 of file ParseLambda.cpp.
References nixf::Token::kind(), nixf::Token::lCur(), nixf::Diagnostic::note(), nixf::Sema::onFormals(), parseFormal(), nixf::Token::range(), and nixf::tok::spelling().
Referenced by parseLambdaArg().
parseInherit()
std::shared_ptr< Inherit > nixf::Parser::parseInherit ()
inherit :  'inherit' '(' expr ')' inherited_attrs ';'
        |  'inherit' inherited_attrs ';'
inherited_attrs: attrname*
Definition at line 91 of file ParseAttrs.cpp.
References nixf::detail::diagNullExpr(), nixf::Token::kind(), nixf::Token::lCur(), parseAttrName(), parseExpr(), nixf::Token::range(), and nixf::tok::spelling().
Referenced by parseBinds().
parseInterpolation()
std::shared_ptr< Interpolation > nixf::Parser::parseInterpolation ()
Parse interpolations.
interpolation : "${" expr "}"
Definition at line 7 of file ParseStrings.cpp.
References nixf::detail::diagNullExpr(), nixf::Token::kind(), nixf::Token::lCur(), parseExpr(), PS_Expr, nixf::Token::range(), and nixf::tok::spelling().
Referenced by parseAttrName(), parseExprPath(), and parseStringParts().
parseLambdaArg()
std::shared_ptr< LambdaArg > nixf::Parser::parseLambdaArg ()
lambda_arg : ID
           | ID @ {' formals '}'
           | '{' formals '}'
           | '{' formals '}' @ ID
Definition at line 85 of file ParseLambda.cpp.
References nixf::Fix::edit(), nixf::Diagnostic::fix(), nixf::Token::kind(), nixf::TextEdit::mkInsertion(), nixf::TextEdit::mkRemoval(), nixf::Diagnostic::note(), parseFormals(), nixf::Token::range(), nixf::tok::spelling(), and nixf::Token::view().
Referenced by parseExprLambda().
parseString()
std::shared_ptr< ExprString > nixf::Parser::parseString (bool IsIndented)
string : " string_part* "
       | '' string_part* ''
Definition at line 89 of file ParseStrings.cpp.
References nixf::Token::kind(), nixf::Token::lCur(), parseStringParts(), PS_IndString, PS_String, nixf::Token::range(), and nixf::tok::spelling().
Referenced by parseAttrName(), and parseExprSimple().
parseStringParts()
std::shared_ptr< InterpolatedParts > nixf::Parser::parseStringParts ()
string_part : interpolation
            | STRING_PART
            | STRING_ESCAPE
Definition at line 59 of file ParseStrings.cpp.
References nixf::Token::kind(), nixf::Token::lCur(), and parseInterpolation().
Referenced by parseString().
The documentation for this class was generated from the following files:
src/Parse/Parser.h
ParseAttrs.cpp
ParseExpr.cpp
ParseLambda.cpp
ParseOp.cpp
ParseSimple.cpp
ParseStrings.cpp
ParseSupport.cpp