nixd: nixf::ExprSelect Class Reference
nixf::ExprSelect Class Reference
#include <Expr.h>
Public Member Functions
ExprSelect (LexerCursorRange Range, std::shared_ptr< Expr > E, std::shared_ptr< AttrPath > Path, std::shared_ptr< Expr > Default)
Expr & expr () const
Expr * defaultExpr () const
AttrPath * path () const
ChildVector children () const override
Public Member Functions inherited from nixf::Expr
bool maybeLambda () const
Public Member Functions inherited from nixf::Node
NodeKind kind () const
LexerCursorRange range () const
PositionRange positionRange () const
LexerCursor lCur () const
LexerCursor rCur () const
const char * name () const
virtual ~Node ()=default
const Node * descend (PositionRange Range) const
Descendant node that contains the given range.
std::string_view src (std::string_view Src) const
Additional Inherited Members
Public Types inherited from nixf::Node
enum NodeKind { NK_BeginExpr , NK_EndExpr }
using ChildVector = boost::container::small_vector<Node *, 8>
Static Public Member Functions inherited from nixf::Expr
static bool classof (const Node *N)
static bool isExpr (NodeKind Kind)
static bool maybeLambda (NodeKind Kind)
Static Public Member Functions inherited from nixf::Node
static const char * name (NodeKind Kind)
Protected Member Functions inherited from nixf::Expr
Expr (NodeKind Kind, LexerCursorRange Range)
Protected Member Functions inherited from nixf::Node
Node (NodeKind Kind, LexerCursorRange Range)
Detailed Description
Definition at line 7 of file Expr.h.
Constructor & Destructor Documentation
ExprSelect()
nixf::ExprSelect::ExprSelect (LexerCursorRange Range, std::shared_ptr< Expr > E, std::shared_ptr< AttrPath > Path, std::shared_ptr< Expr > Default) inline
Definition at line 13 of file Expr.h.
References nixf::Expr::Expr().
Member Function Documentation
children()
ChildVector nixf::ExprSelect::children () const inline nodiscard override virtual
Implements nixf::Node.
Definition at line 29 of file Expr.h.
defaultExpr()
Expr * nixf::ExprSelect::defaultExpr () const inline nodiscard
Definition at line 25 of file Expr.h.
References nixf::Expr::Expr().
expr()
Expr & nixf::ExprSelect::expr () const inline nodiscard
Definition at line 20 of file Expr.h.
References nixf::Expr::Expr().
Referenced by nixd::idioms::mkSelector().
path()
AttrPath * nixf::ExprSelect::path () const inline nodiscard
Definition at line 27 of file Expr.h.
Referenced by nixd::idioms::mkSelector().
The documentation for this class was generated from the following file:
Expr.h