nixd: nixd::Controller Class Reference
nixd::Controller Class Reference
#include <Controller.h>
Public Types
using OptionMapTy = std::map<std::string, std::unique_ptr<AttrSetClientProc>>
Public Member Functions
Controller (std::unique_ptr< lspserver::InboundPort > In, std::unique_ptr< lspserver::OutboundPort > Out)
~Controller () override
bool isReadyToEval ()
Public Member Functions inherited from lspserver::LSPServer
LSPServer (std::unique_ptr< InboundPort > In, std::unique_ptr< OutboundPort > Out)
void closeInbound ()
Close the inbound port.
void run ()
void switchStreamStyle (JSONStreamStyle Style)
Public Member Functions inherited from lspserver::MessageHandler
virtual ~MessageHandler ()=default
Additional Inherited Members
Protected Member Functions inherited from lspserver::LSPServer
template<class T>
llvm::unique_function< void(const T &)> mkOutNotifiction (llvm::StringRef Method, OutboundPort *O=nullptr)
template<class ParamTy, class ResponseTy>
llvm::unique_function< void(const ParamTy &, Callback< ResponseTy >)> mkOutMethod (llvm::StringRef Method, OutboundPort *O=nullptr)
Protected Attributes inherited from lspserver::LSPServer
HandlerRegistry Registry
Detailed Description
Definition at line 19 of file Controller.h.
Member Typedef Documentation
OptionMapTy
using nixd::Controller::OptionMapTy = std::map<std::string, std::unique_ptr<AttrSetClientProc>>
Definition at line 21 of file Controller.h.
Constructor & Destructor Documentation
Controller()
Controller::Controller (std::unique_ptr< lspserver::InboundPort > In, std::unique_ptr< lspserver::OutboundPort > Out)
Definition at line 68 of file Support.cpp.
References lspserver::LSPServer::LSPServer(), lspserver::LSPServer::mkOutMethod(), lspserver::LSPServer::mkOutNotifiction(), and lspserver::LSPServer::Registry.
~Controller()
nixd::Controller::~Controller () inline override
Definition at line 236 of file Controller.h.
Member Function Documentation
isReadyToEval()
bool nixd::Controller::isReadyToEval () inline
Definition at line 238 of file Controller.h.
The documentation for this class was generated from the following files:
Controller.h
CodeAction.cpp
Completion.cpp
Controller/Configuration.cpp
Definition.cpp
Diagnostics.cpp
DocumentHighlight.cpp
DocumentLink.cpp
DocumentSymbol.cpp
FindReferences.cpp
Format.cpp
Hover.cpp
InlayHints.cpp
LifeTime.cpp
Rename.cpp
SemanticTokens.cpp
Support.cpp
TextDocumentSync.cpp