nixd: nixf::InterpolatedParts Class Reference
nixf::InterpolatedParts Class Reference
#include <Simple.h>
Public Member Functions
InterpolatedParts (LexerCursorRange Range, std::vector< InterpolablePart > Fragments)
const std::vector< InterpolablePart > & fragments () const
bool isLiteral () const
const std::string & literal () const
ChildVector children () const override
Public Member Functions inherited from nixf::Node
NodeKind kind () const
LexerCursorRange range () const
PositionRange positionRange () const
LexerCursor lCur () const
LexerCursor rCur () const
const char * name () const
virtual ~Node ()=default
const Node * descend (PositionRange Range) const
Descendant node that contains the given range.
std::string_view src (std::string_view Src) const
Additional Inherited Members
Public Types inherited from nixf::Node
enum NodeKind { NK_BeginExpr , NK_EndExpr }
using ChildVector = boost::container::small_vector<Node *, 8>
Static Public Member Functions inherited from nixf::Node
static const char * name (NodeKind Kind)
Protected Member Functions inherited from nixf::Node
Node (NodeKind Kind, LexerCursorRange Range)
Detailed Description
Definition at line 85 of file Simple.h.
Constructor & Destructor Documentation
InterpolatedParts()
InterpolatedParts::InterpolatedParts (LexerCursorRange Range, std::vector< InterpolablePart > Fragments)
Definition at line 53 of file Nodes.cpp.
References nixf::Node::Node().
Member Function Documentation
children()
ChildVector nixf::InterpolatedParts::children () const inline nodiscard override virtual
Implements nixf::Node.
Definition at line 106 of file Simple.h.
References nixf::InterpolablePart::SPK_Interpolation.
fragments()
const std::vector< InterpolablePart > & nixf::InterpolatedParts::fragments () const inline nodiscard
Definition at line 92 of file Simple.h.
isLiteral()
bool nixf::InterpolatedParts::isLiteral () const inline nodiscard
Definition at line 96 of file Simple.h.
References nixf::InterpolablePart::SPK_Escaped.
Referenced by literal().
literal()
const std::string & nixf::InterpolatedParts::literal () const inline nodiscard
Definition at line 101 of file Simple.h.
References isLiteral().
The documentation for this class was generated from the following files:
Simple.h
Nodes.cpp