nixd: nixf::Token Class Reference
nixf::Token Class Reference
A token. With it's kind, and the range in source code.
#include <Token.h>
Public Member Functions
Token (tok::TokenKind Kind, LexerCursorRange Range, std::string_view View)
LexerCursor lCur () const
LexerCursor rCur () const
tok::TokenKind kind () const
LexerCursorRange range () const
std::string_view view () const
Detailed Description
A token. With it's kind, and the range in source code.
This class is trivially copyable.
Definition at line 14 of file Token.h.
Constructor & Destructor Documentation
Token()
nixf::Token::Token (tok::TokenKind Kind, LexerCursorRange Range, std::string_view View) inline
Definition at line 20 of file Token.h.
Member Function Documentation
kind()
tok::TokenKind nixf::Token::kind () const inline nodiscard
Definition at line 24 of file Token.h.
Referenced by nixf::Parser::parse(), nixf::Parser::parseAttrName(), nixf::Parser::parseAttrPath(), nixf::Parser::parseBinding(), nixf::Parser::parseExprAssert(), nixf::Parser::parseExprAttrs(), nixf::Parser::parseExprIf(), nixf::Parser::parseExprLet(), nixf::Parser::parseExprList(), nixf::Parser::parseExprParen(), nixf::Parser::parseExprPath(), nixf::Parser::parseExprSelect(), nixf::Parser::parseExprSimple(), nixf::Parser::parseExprWith(), nixf::Parser::parseFormal(), nixf::Parser::parseFormals(), nixf::Parser::parseInherit(), nixf::Parser::parseInterpolation(), nixf::Parser::parseLambdaArg(), nixf::Parser::parseString(), and nixf::Parser::parseStringParts().
lCur()
LexerCursor nixf::Token::lCur () const inline nodiscard
Definition at line 22 of file Token.h.
Referenced by nixf::Parser::parseExprList(), nixf::Parser::parseExprParen(), nixf::Parser::parseExprPath(), nixf::Parser::parseExprSimple(), nixf::Parser::parseFormals(), nixf::Parser::parseInherit(), nixf::Parser::parseInterpolation(), and nixf::Parser::parseString().
range()
LexerCursorRange nixf::Token::range () const inline nodiscard
Definition at line 25 of file Token.h.
Referenced by nixf::Parser::parseBinding(), nixf::Parser::parseExprAssert(), nixf::Parser::parseExprAttrs(), nixf::Parser::parseExprIf(), nixf::Parser::parseExprLet(), nixf::Parser::parseExprList(), nixf::Parser::parseExprParen(), nixf::Parser::parseExprSelect(), nixf::Parser::parseExprSimple(), nixf::Parser::parseExprWith(), nixf::Parser::parseFormals(), nixf::Parser::parseInherit(), nixf::Parser::parseInterpolation(), nixf::Parser::parseLambdaArg(), and nixf::Parser::parseString().
rCur()
LexerCursor nixf::Token::rCur () const inline nodiscard
Definition at line 23 of file Token.h.
Referenced by nixf::Parser::parseExprIf(), nixf::Parser::parseExprPath(), nixf::Parser::parseExprSelect(), and nixf::Parser::parseExprSimple().
view()
std::string_view nixf::Token::view () const inline nodiscard
Definition at line 26 of file Token.h.
Referenced by nixf::Parser::parseExprPath(), nixf::Parser::parseExprSimple(), and nixf::Parser::parseLambdaArg().
The documentation for this class was generated from the following file:
Token.h