nixd: nixf::Node Class Reference
nixf::Node Class Reference abstract
#include <Basic.h>
Public Types
enum NodeKind { NK_BeginExpr , NK_EndExpr }
using ChildVector = boost::container::small_vector<Node *, 8>
Public Member Functions
NodeKind kind () const
LexerCursorRange range () const
PositionRange positionRange () const
LexerCursor lCur () const
LexerCursor rCur () const
const char * name () const
virtual ChildVector children () const =0
virtual ~Node ()=default
const Node * descend (PositionRange Range) const
Descendant node that contains the given range.
std::string_view src (std::string_view Src) const
Static Public Member Functions
static const char * name (NodeKind Kind)
Protected Member Functions
Node (NodeKind Kind, LexerCursorRange Range)
Detailed Description
Definition at line 12 of file Basic.h.
Member Typedef Documentation
ChildVector
using nixf::Node::ChildVector = boost::container::small_vector<Node *, 8>
Definition at line 42 of file Basic.h.
Member Enumeration Documentation
NodeKind
enum nixf::Node::NodeKind
Enumerator
NK_BeginExpr
provides NODE(NAME) EXPR(NAME)
${ expr }
Misc node used for parentheses keywords etc.
See also
Misc
NK_EndExpr
provides NODE(NAME) EXPR(NAME)
Definition at line 14 of file Basic.h.
Constructor & Destructor Documentation
Node()
nixf::Node::Node (NodeKind Kind, LexerCursorRange Range) inline explicit protected
Definition at line 30 of file Basic.h.
Referenced by nixf::AttrName::AttrName(), nixf::AttrName::AttrName(), nixf::AttrName::AttrName(), nixf::AttrPath::AttrPath(), nixf::Binding::Binding(), nixf::Binds::Binds(), nixf::Expr::classof(), descend(), nixf::Dot::Dot(), nixf::Expr::Expr(), nixf::Formal::Formal(), nixf::Formal::Formal(), nixf::Formals::Formals(), nixf::Identifier::Identifier(), nixf::Inherit::Inherit(), nixf::InterpolatedParts::InterpolatedParts(), nixf::Interpolation::Interpolation(), nixf::LambdaArg::LambdaArg(), nixf::Misc::Misc(), nixf::Dot::next(), nixf::Op::Op(), and nixf::Dot::prev().
~Node()
virtual nixf::Node::~Node () virtual default
Member Function Documentation
children()
virtual ChildVector nixf::Node::children () const nodiscard pure virtual
Implemented in nixf::AttrName, nixf::AttrPath, nixf::Binding, nixf::Binds, nixf::Dot, nixf::ExprAssert, nixf::ExprAttrs, nixf::ExprBinOp, nixf::ExprCall, nixf::ExprFloat, nixf::ExprIf, nixf::ExprInt, nixf::ExprLambda, nixf::ExprLet, nixf::ExprList, nixf::ExprOp, nixf::ExprOpHasAttr, nixf::ExprParen, nixf::ExprPath, nixf::ExprSelect, nixf::ExprSPath, nixf::ExprString, nixf::ExprUnaryOp, nixf::ExprVar, nixf::ExprWith, nixf::Formal, nixf::Formals, nixf::Identifier, nixf::Inherit, nixf::InterpolatedParts, nixf::Interpolation, nixf::LambdaArg, nixf::Misc, and nixf::Op.
Referenced by descend().
descend()
const Node * nixf::Node::descend (PositionRange Range) const inline nodiscard
Descendant node that contains the given range.
Definition at line 49 of file Basic.h.
References children(), Node(), and positionRange().
kind()
NodeKind nixf::Node::kind () const inline nodiscard
Definition at line 34 of file Basic.h.
Referenced by nixf::Expr::classof(), nixd::findDefinition(), nixd::getScopeAndPrefix(), nixd::havePackageScope(), nixf::Expr::maybeLambda(), nixd::idioms::mkSelector(), nixd::idioms::mkVarSelector(), nixf::ParentMapAnalysis::upExpr(), and nixf::ParentMapAnalysis::upTo().
lCur()
LexerCursor nixf::Node::lCur () const inline nodiscard
Definition at line 37 of file Basic.h.
Referenced by nixf::Sema::checkFormalSep(), nixf::Parser::parseExprSelect(), and src().
name() [1/2]
const char * nixf::Node::name () const inline nodiscard
Definition at line 40 of file Basic.h.
References name().
Referenced by name().
name() [2/2]
const char * Node::name (NodeKind Kind) static nodiscard
provides NODE(NAME) EXPR(NAME)
${ expr }
Misc node used for parentheses keywords etc.
See also
Misc
Definition at line 35 of file Nodes.cpp.
positionRange()
PositionRange nixf::Node::positionRange () const inline nodiscard
Definition at line 36 of file Basic.h.
Referenced by descend().
range()
LexerCursorRange nixf::Node::range () const inline nodiscard
Definition at line 35 of file Basic.h.
Referenced by nixf::AttrName::AttrName(), nixf::AttrName::AttrName(), nixf::Sema::checkAttrRecursiveForMerge(), nixf::Sema::checkFormalEllipsis(), nixf::Sema::checkFormalEmpty(), nixf::Sema::checkFormalSep(), nixf::Sema::dedupFormal(), nixf::Parser::parseExprLet(), and nixf::Sema::removeFormal().
rCur()
LexerCursor nixf::Node::rCur () const inline nodiscard
Definition at line 38 of file Basic.h.
Referenced by nixf::Sema::checkFormalEllipsis(), and src().
src()
std::string_view nixf::Node::src (std::string_view Src) const inline nodiscard
Definition at line 63 of file Basic.h.
References lCur(), nixf::LexerCursor::offset(), and rCur().
Referenced by nixf::Sema::checkFormalEllipsis().
The documentation for this class was generated from the following files:
Basic.h
Nodes.cpp