nixd: nixf::PartialDiagnostic Class Reference
nixf::PartialDiagnostic Class Reference abstract
#include <Diagnostic.h>
Public Member Functions
virtual const char * message () const =0
virtual ~PartialDiagnostic ()=default
PartialDiagnostic & operator<< (std::string Var)
std::string format () const
const std::vector< std::string > & args () const
std::vector< std::string > & args ()
void tag (DiagnosticTag Tag)
const std::vector< DiagnosticTag > & tags () const
LexerCursorRange range () const
Protected Member Functions
PartialDiagnostic ()=default
PartialDiagnostic (LexerCursorRange Range)
Detailed Description
Definition at line 79 of file Diagnostic.h.
Constructor & Destructor Documentation
~PartialDiagnostic()
virtual nixf::PartialDiagnostic::~PartialDiagnostic () virtual default
PartialDiagnostic() [1/2]
nixf::PartialDiagnostic::PartialDiagnostic () protected default
Referenced by nixf::Diagnostic::Diagnostic(), nixf::Note::Note(), nixf::Note::operator<<(), and operator<<().
PartialDiagnostic() [2/2]
nixf::PartialDiagnostic::PartialDiagnostic (LexerCursorRange Range) inline protected
Definition at line 105 of file Diagnostic.h.
Member Function Documentation
args() [1/2]
std::vector< std::string > & nixf::PartialDiagnostic::args () inline
Definition at line 94 of file Diagnostic.h.
args() [2/2]
const std::vector< std::string > & nixf::PartialDiagnostic::args () const inline nodiscard
Definition at line 92 of file Diagnostic.h.
Referenced by nixf::Note::operator<<().
format()
std::string PartialDiagnostic::format () const nodiscard
Definition at line 51 of file Diagnostic.cpp.
References message().
message()
virtual const char * nixf::PartialDiagnostic::message () const nodiscard pure virtual
Implemented in nixf::Diagnostic, and nixf::Note.
Referenced by format().
operator<<()
PartialDiagnostic & nixf::PartialDiagnostic::operator<< (std::string Var) inline
Definition at line 85 of file Diagnostic.h.
References PartialDiagnostic().
range()
LexerCursorRange nixf::PartialDiagnostic::range () const inline nodiscard
Definition at line 100 of file Diagnostic.h.
tag()
void nixf::PartialDiagnostic::tag (DiagnosticTag Tag) inline
Definition at line 96 of file Diagnostic.h.
Referenced by nixf::Sema::checkFormalEmpty(), nixf::Sema::lowerInheritName(), nixf::Parser::parseExprParen(), and nixf::Parser::parseInherit().
tags()
const std::vector< DiagnosticTag > & nixf::PartialDiagnostic::tags () const inline nodiscard
Definition at line 98 of file Diagnostic.h.
The documentation for this class was generated from the following files:
Diagnostic.h
Diagnostic.cpp