nixd: lspserver::LSPServer Class Reference
lspserver::LSPServer Class Reference
#include <LSPServer.h>
Public Member Functions
LSPServer (std::unique_ptr< InboundPort > In, std::unique_ptr< OutboundPort > Out)
void closeInbound ()
Close the inbound port.
void run ()
void switchStreamStyle (JSONStreamStyle Style)
Public Member Functions inherited from lspserver::MessageHandler
virtual ~MessageHandler ()=default
Protected Member Functions
template<class T>
llvm::unique_function< void(const T &)> mkOutNotifiction (llvm::StringRef Method, OutboundPort *O=nullptr)
template<class ParamTy, class ResponseTy>
llvm::unique_function< void(const ParamTy &, Callback< ResponseTy >)> mkOutMethod (llvm::StringRef Method, OutboundPort *O=nullptr)
Protected Attributes
HandlerRegistry Registry
Detailed Description
LSPServer wraps inputs & outputs, associate message IDs between calls/reply, and provide type-safe interfaces.
Definition at line 17 of file LSPServer.h.
Constructor & Destructor Documentation
LSPServer()
lspserver::LSPServer::LSPServer (std::unique_ptr< InboundPort > In, std::unique_ptr< OutboundPort > Out) inline
Definition at line 87 of file LSPServer.h.
Referenced by nixd::AttrSetClient::AttrSetClient(), nixd::AttrSetProvider::AttrSetProvider(), and nixd::Controller::Controller().
Member Function Documentation
closeInbound()
void lspserver::LSPServer::closeInbound () inline
Close the inbound port.
Definition at line 91 of file LSPServer.h.
Referenced by nixd::OwnedEvalClient::~OwnedEvalClient().
mkOutMethod()
template<class ParamTy, class ResponseTy> llvm::unique_function< void(const ParamTy &, Callback< ResponseTy >)> lspserver::LSPServer::mkOutMethod (llvm::StringRef Method, OutboundPort * O = nullptr) inline protected
Definition at line 69 of file LSPServer.h.
References lspserver::Method, and lspserver::parseParam().
Referenced by nixd::AttrSetClient::AttrSetClient(), and nixd::Controller::Controller().
mkOutNotifiction()
template<class T> llvm::unique_function< void(const T &)> lspserver::LSPServer::mkOutNotifiction (llvm::StringRef Method, OutboundPort * O = nullptr) inline protected
Definition at line 58 of file LSPServer.h.
References lspserver::log(), lspserver::Method, and lspserver::OutboundPort::notify().
Referenced by nixd::AttrSetClient::AttrSetClient(), and nixd::Controller::Controller().
run()
void lspserver::LSPServer::run ()
Definition at line 15 of file LSPServer.cpp.
Referenced by main(), main(), and nixd::OwnedEvalClient::OwnedEvalClient().
switchStreamStyle()
void lspserver::LSPServer::switchStreamStyle (JSONStreamStyle Style) inline
Definition at line 94 of file LSPServer.h.
Member Data Documentation
Registry
HandlerRegistry lspserver::LSPServer::Registry protected
Definition at line 55 of file LSPServer.h.
Referenced by nixd::Controller::Controller().
The documentation for this class was generated from the following files:
LSPServer.h
LSPServer.cpp