nixd: nixf::Position Class Reference
nixf::Position Class Reference
#include <Range.h>
Public Member Functions
Position ()=default
Position (int64_t Line, int64_t Column)
int64_t line () const
int64_t column () const
Friends
bool operator== (const Position &LHS, const Position &RHS)
bool operator< (const Position &LHS, const Position &RHS)
bool operator<= (const Position &LHS, const Position &RHS)
Detailed Description
Definition at line 8 of file Range.h.
Constructor & Destructor Documentation
Position() [1/2]
nixf::Position::Position () default
Referenced by operator<, operator<=, and operator==.
Position() [2/2]
nixf::Position::Position (int64_t Line, int64_t Column) inline
Definition at line 14 of file Range.h.
Member Function Documentation
column()
int64_t nixf::Position::column () const inline nodiscard
Definition at line 17 of file Range.h.
line()
int64_t nixf::Position::line () const inline nodiscard
Definition at line 16 of file Range.h.
Friends And Related Symbol Documentation
operator<
bool operator< (const Position & LHS, const Position & RHS) friend
Definition at line 23 of file Range.h.
References Position().
operator<=
bool operator<= (const Position & LHS, const Position & RHS) friend
Definition at line 28 of file Range.h.
References Position().
operator==
bool operator== (const Position & LHS, const Position & RHS) friend
Definition at line 19 of file Range.h.
References Position().
The documentation for this class was generated from the following file:
Range.h