nixd: lspserver::MessageHandler Class Reference
lspserver::MessageHandler Class Reference abstract
#include <Connection.h>
Public Member Functions
virtual ~MessageHandler ()=default
virtual bool onNotify (llvm::StringRef Method, llvm::json::Value)=0
virtual bool onCall (llvm::StringRef Method, llvm::json::Value Params, llvm::json::Value ID)=0
virtual bool onReply (llvm::json::Value ID, llvm::Expected< llvm::json::Value > Result)=0
Detailed Description
Parsed & classfied messages are dispatched to this handler class LSP Servers should inherit from this handler and dispatch notify/call/reply to implementations.
Definition at line 23 of file Connection.h.
Constructor & Destructor Documentation
~MessageHandler()
virtual lspserver::MessageHandler::~MessageHandler () virtual default
Member Function Documentation
onCall()
virtual bool lspserver::MessageHandler::onCall (llvm::StringRef Method, llvm::json::Value Params, llvm::json::Value ID) pure virtual
References lspserver::Method.
Referenced by lspserver::InboundPort::dispatch().
onNotify()
virtual bool lspserver::MessageHandler::onNotify (llvm::StringRef Method, llvm::json::Value) pure virtual
References lspserver::Method.
Referenced by lspserver::InboundPort::dispatch().
onReply()
virtual bool lspserver::MessageHandler::onReply (llvm::json::Value ID, llvm::Expected< llvm::json::Value > Result) pure virtual
Referenced by lspserver::InboundPort::dispatch().
The documentation for this class was generated from the following file:
Connection.h