nixd: nixd::util::AutoCloseFD Class Reference
nixd::util::AutoCloseFD Class Reference
File Descriptor RAII wrapper.
#include <AutoCloseFD.h>
Public Types
using FDTy = int
Public Member Functions
AutoCloseFD (FDTy FD)
AutoCloseFD (const AutoCloseFD &)=delete
AutoCloseFD (AutoCloseFD &&That) noexcept
bool isReleased () const
~AutoCloseFD ()
FDTy get () const
void release ()
Static Public Member Functions
static bool isReleased (FDTy FD)
Detailed Description
File Descriptor RAII wrapper.
Definition at line 8 of file AutoCloseFD.h.
Member Typedef Documentation
FDTy
using nixd::util::AutoCloseFD::FDTy = int
Definition at line 10 of file AutoCloseFD.h.
Constructor & Destructor Documentation
AutoCloseFD() [1/3]
nixd::util::AutoCloseFD::AutoCloseFD (FDTy FD)
Definition at line 24 of file AutoCloseFD.cpp.
Referenced by AutoCloseFD(), and AutoCloseFD().
AutoCloseFD() [2/3]
nixd::util::AutoCloseFD::AutoCloseFD (const AutoCloseFD &) delete
References AutoCloseFD().
AutoCloseFD() [3/3]
nixd::util::AutoCloseFD::AutoCloseFD (AutoCloseFD && That) noexcept
Definition at line 12 of file AutoCloseFD.cpp.
References AutoCloseFD().
~AutoCloseFD()
nixd::util::AutoCloseFD::~AutoCloseFD ()
Definition at line 7 of file AutoCloseFD.cpp.
Member Function Documentation
get()
AutoCloseFD::FDTy nixd::util::AutoCloseFD::get () const nodiscard
Definition at line 16 of file AutoCloseFD.cpp.
isReleased() [1/2]
bool nixd::util::AutoCloseFD::isReleased () const nodiscard
Definition at line 22 of file AutoCloseFD.cpp.
References isReleased().
Referenced by isReleased().
isReleased() [2/2]
bool nixd::util::AutoCloseFD::isReleased (FDTy FD) static
Definition at line 20 of file AutoCloseFD.cpp.
release()
void nixd::util::AutoCloseFD::release ()
Definition at line 18 of file AutoCloseFD.cpp.
The documentation for this class was generated from the following files:
AutoCloseFD.h
AutoCloseFD.cpp