nixd: lspserver::LoggingSession Class Reference
lspserver::LoggingSession Class Reference
Only one LoggingSession can be active at a time.
#include <Logger.h>
Public Member Functions
LoggingSession (Logger &Instance)
~LoggingSession ()
LoggingSession (LoggingSession &&)=delete
LoggingSession & operator= (LoggingSession &&)=delete
LoggingSession (LoggingSession const &)=delete
LoggingSession & operator= (LoggingSession const &)=delete
Detailed Description
Only one LoggingSession can be active at a time.
Definition at line 91 of file Logger.h.
Constructor & Destructor Documentation
LoggingSession() [1/3]
lspserver::LoggingSession::LoggingSession (Logger & Instance)
Definition at line 30 of file Logger.cpp.
Referenced by LoggingSession(), LoggingSession(), operator=(), and operator=().
~LoggingSession()
lspserver::LoggingSession::~LoggingSession ()
Definition at line 35 of file Logger.cpp.
LoggingSession() [2/3]
lspserver::LoggingSession::LoggingSession (LoggingSession &&) delete
References LoggingSession().
LoggingSession() [3/3]
lspserver::LoggingSession::LoggingSession (LoggingSession const &) delete
References LoggingSession().
Member Function Documentation
operator=() [1/2]
LoggingSession & lspserver::LoggingSession::operator= (LoggingSession &&) delete
References LoggingSession().
operator=() [2/2]
LoggingSession & lspserver::LoggingSession::operator= (LoggingSession const &) delete
References LoggingSession().
The documentation for this class was generated from the following files:
Logger.h
Logger.cpp