nixd: lspserver::URI Class Reference
lspserver::URI Class Reference
#include <URI.h>
Public Member Functions
URI (llvm::StringRef Scheme, llvm::StringRef Authority, llvm::StringRef Body)
llvm::StringRef scheme () const
Returns decoded scheme e.g. "https".
llvm::StringRef authority () const
Returns decoded authority e.g. "reviews.lvm.org".
llvm::StringRef body () const
Returns decoded body e.g. "/D41946".
std::string toString () const
Returns a string URI with all components percent-encoded.
Static Public Member Functions
static llvm::Expected< URI > create (llvm::StringRef AbsolutePath, llvm::StringRef Scheme)
static URI create (llvm::StringRef AbsolutePath)
static URI createFile (llvm::StringRef AbsolutePath)
This creates a file:// URI for AbsolutePath. The path must be absolute.
static llvm::Expected< URI > parse (llvm::StringRef Uri)
static llvm::Expected< std::string > resolve (const URI &U, llvm::StringRef HintPath="")
static llvm::Expected< std::string > resolve (llvm::StringRef FileURI, llvm::StringRef HintPath="")
Same as above, in addition it parses the FileURI using URI::parse.
static llvm::Expected< std::string > resolvePath (llvm::StringRef AbsPath, llvm::StringRef HintPath="")
static llvm::Expected< std::string > includeSpelling (const URI &U)
Friends
bool operator== (const URI &LHS, const URI &RHS)
bool operator< (const URI &LHS, const URI &RHS)
Detailed Description
A URI describes the location of a source file. In the simplest case, this is a "file" URI that directly encodes the absolute path to a file. More abstract cases are possible: a shared index service might expose repo:// URIs that are relative to the source control root.
Clangd handles URIs of the form <scheme>:[//<authority>]<body>. It doesn't further split the authority or body into constituent parts (e.g. query strings is included in the body).
Definition at line 18 of file URI.h.
Constructor & Destructor Documentation
URI()
lspserver::URI::URI (llvm::StringRef Scheme, llvm::StringRef Authority, llvm::StringRef Body)
Definition at line 150 of file URI.cpp.
References URI().
Referenced by create(), createFile(), includeSpelling(), operator<, operator==, parse(), resolve(), and URI().
Member Function Documentation
authority()
llvm::StringRef lspserver::URI::authority () const inline
Returns decoded authority e.g. "reviews.lvm.org".
Definition at line 25 of file URI.h.
body()
llvm::StringRef lspserver::URI::body () const inline
Returns decoded body e.g. "/D41946".
Definition at line 27 of file URI.h.
create() [1/2]
URI lspserver::URI::create (llvm::StringRef AbsolutePath) static
Definition at line 216 of file URI.cpp.
References createFile(), and URI().
create() [2/2]
llvm::Expected< URI > lspserver::URI::create (llvm::StringRef AbsolutePath, llvm::StringRef Scheme) static
Creates a URI for a file in the given scheme. Scheme must be registered. The URI is percent-encoded.
Definition at line 206 of file URI.cpp.
References lspserver::error().
createFile()
URI lspserver::URI::createFile (llvm::StringRef AbsolutePath) static
This creates a file:// URI for AbsolutePath. The path must be absolute.
Definition at line 235 of file URI.cpp.
References URI().
Referenced by create(), and lspserver::URIForFile::uri().
includeSpelling()
llvm::Expected< std::string > lspserver::URI::includeSpelling (const URI & U) static
Gets the preferred spelling of this file for #include, if there is one, e.g. <system_header.h>, "path/to/x.h".
This allows URI schemas to provide their customized include paths.
Returns an empty string if normal include-shortening based on the absolute path should be used. Fails if the URI is not valid in the schema.
Definition at line 270 of file URI.cpp.
References URI().
parse()
llvm::Expected< URI > lspserver::URI::parse (llvm::StringRef Uri) static
Parse a URI string "<scheme>:[//<authority>/]<path>". Percent-encoded characters in the URI will be decoded.
Definition at line 174 of file URI.cpp.
References lspserver::error(), and URI().
Referenced by lspserver::fromJSON(), and resolve().
resolve() [1/2]
llvm::Expected< std::string > lspserver::URI::resolve (const URI & U, llvm::StringRef HintPath = "") static
Resolves the absolute path of U. If there is no matching scheme, or the URI is invalid in the scheme, this returns an error.
HintPath A related path, such as the current file or working directory, which can help disambiguate when the same file exists in many workspaces.
Definition at line 242 of file URI.cpp.
References URI().
Referenced by lspserver::URIForFile::fromURI(), and resolve().
resolve() [2/2]
llvm::Expected< std::string > lspserver::URI::resolve (llvm::StringRef FileURI, llvm::StringRef HintPath = "") static
Same as above, in addition it parses the FileURI using URI::parse.
Definition at line 195 of file URI.cpp.
References parse(), and resolve().
resolvePath()
llvm::Expected< std::string > lspserver::URI::resolvePath (llvm::StringRef AbsPath, llvm::StringRef HintPath = "") static
Resolves AbsPath into a canonical path of its URI, by converting AbsPath to URI and resolving the URI to get th canonical path. This ensures that paths with the same URI are resolved into consistent file path.
Definition at line 250 of file URI.cpp.
Referenced by lspserver::URIForFile::canonicalize().
scheme()
llvm::StringRef lspserver::URI::scheme () const inline
Returns decoded scheme e.g. "https".
Definition at line 23 of file URI.h.
toString()
std::string lspserver::URI::toString () const
Returns a string URI with all components percent-encoded.
Definition at line 158 of file URI.cpp.
Referenced by lspserver::URIForFile::uri().
Friends And Related Symbol Documentation
operator<
bool operator< (const URI & LHS, const URI & RHS) friend
Definition at line 82 of file URI.h.
References URI().
operator==
bool operator== (const URI & LHS, const URI & RHS) friend
Definition at line 77 of file URI.h.
References URI().
The documentation for this class was generated from the following files:
URI.h
URI.cpp