nixd: nixf::ExprWith Class Reference
nixf::ExprWith Class Reference
#include <Expr.h>
Public Member Functions
ExprWith (LexerCursorRange Range, std::shared_ptr< Misc > KwWith, std::shared_ptr< Misc > TokSemi, std::shared_ptr< Expr > With, std::shared_ptr< Expr > E)
const Misc & kwWith () const
const Misc * tokSemi () const
Expr * with () const
Expr * expr () const
ChildVector children () const override
Public Member Functions inherited from nixf::Expr
bool maybeLambda () const
Public Member Functions inherited from nixf::Node
NodeKind kind () const
LexerCursorRange range () const
PositionRange positionRange () const
LexerCursor lCur () const
LexerCursor rCur () const
const char * name () const
virtual ~Node ()=default
const Node * descend (PositionRange Range) const
Descendant node that contains the given range.
std::string_view src (std::string_view Src) const
Additional Inherited Members
Public Types inherited from nixf::Node
enum NodeKind { NK_BeginExpr , NK_EndExpr }
using ChildVector = boost::container::small_vector<Node *, 8>
Static Public Member Functions inherited from nixf::Expr
static bool classof (const Node *N)
static bool isExpr (NodeKind Kind)
static bool maybeLambda (NodeKind Kind)
Static Public Member Functions inherited from nixf::Node
static const char * name (NodeKind Kind)
Protected Member Functions inherited from nixf::Expr
Expr (NodeKind Kind, LexerCursorRange Range)
Protected Member Functions inherited from nixf::Node
Node (NodeKind Kind, LexerCursorRange Range)
Detailed Description
Definition at line 157 of file Expr.h.
Constructor & Destructor Documentation
ExprWith()
nixf::ExprWith::ExprWith (LexerCursorRange Range, std::shared_ptr< Misc > KwWith, std::shared_ptr< Misc > TokSemi, std::shared_ptr< Expr > With, std::shared_ptr< Expr > E) inline
Definition at line 164 of file Expr.h.
References nixf::Expr::Expr().
Member Function Documentation
children()
ChildVector nixf::ExprWith::children () const inline nodiscard override virtual
Implements nixf::Node.
Definition at line 175 of file Expr.h.
expr()
Expr * nixf::ExprWith::expr () const inline nodiscard
Definition at line 173 of file Expr.h.
References nixf::Expr::Expr().
kwWith()
const Misc & nixf::ExprWith::kwWith () const inline nodiscard
Definition at line 170 of file Expr.h.
tokSemi()
const Misc * nixf::ExprWith::tokSemi () const inline nodiscard
Definition at line 171 of file Expr.h.
with()
Expr * nixf::ExprWith::with () const inline nodiscard
Definition at line 172 of file Expr.h.
References nixf::Expr::Expr().
Referenced by nixd::havePackageScope().
The documentation for this class was generated from the following file:
Expr.h