nixd: nixf::Identifier Class Reference
nixf::Identifier Class Reference
Identifier. Variable names, attribute names, etc.
#include <Basic.h>
Public Member Functions
Identifier (LexerCursorRange Range, std::string Name)
const std::string & name () const
ChildVector children () const override
Public Member Functions inherited from nixf::Node
NodeKind kind () const
LexerCursorRange range () const
PositionRange positionRange () const
LexerCursor lCur () const
LexerCursor rCur () const
const char * name () const
virtual ~Node ()=default
const Node * descend (PositionRange Range) const
Descendant node that contains the given range.
std::string_view src (std::string_view Src) const
Additional Inherited Members
Public Types inherited from nixf::Node
enum NodeKind { NK_BeginExpr , NK_EndExpr }
using ChildVector = boost::container::small_vector<Node *, 8>
Static Public Member Functions inherited from nixf::Node
static const char * name (NodeKind Kind)
Protected Member Functions inherited from nixf::Node
Node (NodeKind Kind, LexerCursorRange Range)
Detailed Description
Identifier. Variable names, attribute names, etc.
Definition at line 114 of file Basic.h.
Constructor & Destructor Documentation
Identifier()
nixf::Identifier::Identifier (LexerCursorRange Range, std::string Name) inline
Definition at line 118 of file Basic.h.
References nixf::Node::Node().
Member Function Documentation
children()
ChildVector nixf::Identifier::children () const inline nodiscard override virtual
Implements nixf::Node.
Definition at line 122 of file Basic.h.
name()
const std::string & nixf::Identifier::name () const inline nodiscard
Definition at line 120 of file Basic.h.
Referenced by nixf::Sema::dedupFormal(), nixd::havePackageScope(), and nixd::idioms::mkVarSelector().
The documentation for this class was generated from the following file:
Basic.h