nixd: nixf::Dot Class Reference
nixf::Dot Class Reference
Holds a "." in the language.
#include <Basic.h>
Public Member Functions
Dot (LexerCursorRange Range, const Node *Prev, const Node *Next)
ChildVector children () const override
const Node & prev () const
const Node * next () const
Public Member Functions inherited from nixf::Node
NodeKind kind () const
LexerCursorRange range () const
PositionRange positionRange () const
LexerCursor lCur () const
LexerCursor rCur () const
const char * name () const
virtual ~Node ()=default
const Node * descend (PositionRange Range) const
Descendant node that contains the given range.
std::string_view src (std::string_view Src) const
Additional Inherited Members
Public Types inherited from nixf::Node
enum NodeKind { NK_BeginExpr , NK_EndExpr }
using ChildVector = boost::container::small_vector<Node *, 8>
Static Public Member Functions inherited from nixf::Node
static const char * name (NodeKind Kind)
Protected Member Functions inherited from nixf::Node
Node (NodeKind Kind, LexerCursorRange Range)
Detailed Description
Holds a "." in the language.
Definition at line 126 of file Basic.h.
Constructor & Destructor Documentation
Dot()
nixf::Dot::Dot (LexerCursorRange Range, const Node * Prev, const Node * Next) inline
Definition at line 131 of file Basic.h.
References nixf::Node::Node().
Member Function Documentation
children()
ChildVector nixf::Dot::children () const inline nodiscard override virtual
Implements nixf::Node.
Definition at line 136 of file Basic.h.
next()
const Node * nixf::Dot::next () const inline nodiscard
Definition at line 142 of file Basic.h.
References nixf::Node::Node().
prev()
const Node & nixf::Dot::prev () const inline nodiscard
Definition at line 138 of file Basic.h.
References nixf::Node::Node().
The documentation for this class was generated from the following file:
Basic.h