nixd: nixd::AttrSetClient Class Reference
nixd::AttrSetClient Class Reference
#include <AttrSetClient.h>
Public Member Functions
AttrSetClient (std::unique_ptr< lspserver::InboundPort > In, std::unique_ptr< lspserver::OutboundPort > Out)
void evalExpr (const EvalExprParams &Params, lspserver::Callback< EvalExprResponse > Reply)
Request eval some expression. The expression should be evaluted to attrset.
void attrpathInfo (const AttrPathInfoParams &Params, lspserver::Callback< AttrPathInfoResponse > Reply)
void attrpathComplete (const AttrPathCompleteParams &Params, lspserver::Callback< AttrPathCompleteResponse > Reply)
void optionInfo (const AttrPathInfoParams &Params, lspserver::Callback< OptionInfoResponse > Reply)
void optionComplete (const AttrPathCompleteParams &Params, lspserver::Callback< OptionCompleteResponse > Reply)
void exit ()
Public Member Functions inherited from lspserver::LSPServer
LSPServer (std::unique_ptr< InboundPort > In, std::unique_ptr< OutboundPort > Out)
void closeInbound ()
Close the inbound port.
void run ()
void switchStreamStyle (JSONStreamStyle Style)
Public Member Functions inherited from lspserver::MessageHandler
virtual ~MessageHandler ()=default
Static Public Member Functions
static const char * getExe ()
Additional Inherited Members
Protected Member Functions inherited from lspserver::LSPServer
template<class T>
llvm::unique_function< void(const T &)> mkOutNotifiction (llvm::StringRef Method, OutboundPort *O=nullptr)
template<class ParamTy, class ResponseTy>
llvm::unique_function< void(const ParamTy &, Callback< ResponseTy >)> mkOutMethod (llvm::StringRef Method, OutboundPort *O=nullptr)
Protected Attributes inherited from lspserver::LSPServer
HandlerRegistry Registry
Detailed Description
Definition at line 12 of file AttrSetClient.h.
Constructor & Destructor Documentation
AttrSetClient()
AttrSetClient::AttrSetClient (std::unique_ptr< lspserver::InboundPort > In, std::unique_ptr< lspserver::OutboundPort > Out)
Definition at line 10 of file AttrSetClient.cpp.
References nixd::rpcMethod::AttrPathComplete, nixd::rpcMethod::AttrPathInfo, nixd::rpcMethod::EvalExpr, nixd::rpcMethod::Exit, lspserver::LSPServer::LSPServer(), lspserver::LSPServer::mkOutMethod(), lspserver::LSPServer::mkOutNotifiction(), nixd::rpcMethod::OptionComplete, and nixd::rpcMethod::OptionInfo.
Member Function Documentation
attrpathComplete()
void nixd::AttrSetClient::attrpathComplete (const AttrPathCompleteParams & Params, lspserver::Callback< AttrPathCompleteResponse > Reply) inline
Definition at line 53 of file AttrSetClient.h.
attrpathInfo()
void nixd::AttrSetClient::attrpathInfo (const AttrPathInfoParams & Params, lspserver::Callback< AttrPathInfoResponse > Reply) inline
Definition at line 48 of file AttrSetClient.h.
evalExpr()
void nixd::AttrSetClient::evalExpr (const EvalExprParams & Params, lspserver::Callback< EvalExprResponse > Reply) inline
Request eval some expression. The expression should be evaluted to attrset.
Definition at line 43 of file AttrSetClient.h.
exit()
void nixd::AttrSetClient::exit () inline
Definition at line 68 of file AttrSetClient.h.
getExe()
const char * AttrSetClient::getExe () static
Get executable path for launching the server.
Returns
null terminated string.
Definition at line 26 of file AttrSetClient.cpp.
Referenced by nixd::startAttrSetEval().
optionComplete()
void nixd::AttrSetClient::optionComplete (const AttrPathCompleteParams & Params, lspserver::Callback< OptionCompleteResponse > Reply) inline
Definition at line 63 of file AttrSetClient.h.
optionInfo()
void nixd::AttrSetClient::optionInfo (const AttrPathInfoParams & Params, lspserver::Callback< OptionInfoResponse > Reply) inline
Definition at line 58 of file AttrSetClient.h.
The documentation for this class was generated from the following files:
AttrSetClient.h
AttrSetClient.cpp