nixd: nixf::Note Class Reference
nixf::Note Class Reference
#include <Diagnostic.h>
Public Types
enum NoteKind { DIAG_NOTE , DIAG_NOTE }
Internal kind.
Public Member Functions
Note (NoteKind Kind, LexerCursorRange Range)
template<class T>
PartialDiagnostic & operator<< (const T &Var)
virtual const char * sname () const
NoteKind kind () const
const char * message () const override
Public Member Functions inherited from nixf::PartialDiagnostic
virtual ~PartialDiagnostic ()=default
PartialDiagnostic & operator<< (std::string Var)
std::string format () const
const std::vector< std::string > & args () const
std::vector< std::string > & args ()
void tag (DiagnosticTag Tag)
const std::vector< DiagnosticTag > & tags () const
LexerCursorRange range () const
Static Public Member Functions
static const char * sname (NoteKind Kind)
static const char * message (NoteKind Kind)
Additional Inherited Members
Protected Member Functions inherited from nixf::PartialDiagnostic
PartialDiagnostic ()=default
PartialDiagnostic (LexerCursorRange Range)
Detailed Description
Definition at line 114 of file Diagnostic.h.
Member Enumeration Documentation
NoteKind
enum nixf::Note::NoteKind
Internal kind.
Enumerator
DIAG_NOTE
DiagnosticNodes.inc, note declarations.
DIAG_NOTE
DiagnosticNodes.inc, note declarations.
Definition at line 117 of file Diagnostic.h.
Constructor & Destructor Documentation
Note()
nixf::Note::Note (NoteKind Kind, LexerCursorRange Range) inline
Definition at line 123 of file Diagnostic.h.
References nixf::PartialDiagnostic::PartialDiagnostic().
Member Function Documentation
kind()
NoteKind nixf::Note::kind () const inline nodiscard
Definition at line 135 of file Diagnostic.h.
Referenced by message(), and sname().
message() [1/2]
const char * nixf::Note::message () const inline nodiscard override virtual
Implements nixf::PartialDiagnostic.
Definition at line 139 of file Diagnostic.h.
References kind(), and message().
Referenced by message().
message() [2/2]
const char * nixf::Note::message (NoteKind Kind) static nodiscard
DiagnosticNodes.inc, note declarations
Definition at line 39 of file Diagnostic.cpp.
operator<<()
template<class T> PartialDiagnostic & nixf::Note::operator<< (const T & Var) inline
Definition at line 126 of file Diagnostic.h.
References nixf::PartialDiagnostic::args(), and nixf::PartialDiagnostic::PartialDiagnostic().
sname() [1/2]
virtual const char * nixf::Note::sname () const inline nodiscard virtual
Definition at line 133 of file Diagnostic.h.
References kind(), and sname().
Referenced by sname().
sname() [2/2]
const char * nixf::Note::sname (NoteKind Kind) static nodiscard
DiagnosticNodes.inc, note declarations
Definition at line 27 of file Diagnostic.cpp.
The documentation for this class was generated from the following files:
Diagnostic.h
Diagnostic.cpp