nixd: lspserver::Key< Type > Class Template Reference
lspserver::Key< Type > Class Template Reference
#include <SourceCode.h>
Public Member Functions
constexpr Key ()=default
Key (Key const &)=delete
Key & operator= (Key const &)=delete
Key (Key &&)=delete
Key & operator= (Key &&)=delete
Detailed Description
template<class Type>
class lspserver::Key< Type >
Definition at line 24 of file SourceCode.h.
Constructor & Destructor Documentation
Key() [1/3]
template<class Type> lspserver::Key< Type >::Key () constexpr default
Referenced by Key(), Key(), operator=(), and operator=().
Key() [2/3]
template<class Type> lspserver::Key< Type >::Key (Key< Type > const &) delete
References Key().
Key() [3/3]
template<class Type> lspserver::Key< Type >::Key (Key< Type > &&) delete
References Key().
Member Function Documentation
operator=() [1/2]
template<class Type> Key & lspserver::Key< Type >::operator= (Key< Type > &&) delete
References Key().
operator=() [2/2]
template<class Type> Key & lspserver::Key< Type >::operator= (Key< Type > const &) delete
References Key().
The documentation for this class was generated from the following file:
SourceCode.h