nixd: nixf::PositionRange Class Reference
nixf::PositionRange Class Reference
#include <Range.h>
Public Member Functions
PositionRange ()=default
PositionRange (Position Begin, Position End)
PositionRange (Position Pos)
Position begin () const
Position end () const
bool contains (const PositionRange &Pos) const
Check if the range contains another range.
Detailed Description
Definition at line 33 of file Range.h.
Constructor & Destructor Documentation
PositionRange() [1/3]
nixf::PositionRange::PositionRange () default
Referenced by contains().
PositionRange() [2/3]
nixf::PositionRange::PositionRange (Position Begin, Position End) inline
Definition at line 40 of file Range.h.
PositionRange() [3/3]
nixf::PositionRange::PositionRange (Position Pos) inline explicit
Definition at line 41 of file Range.h.
Member Function Documentation
begin()
Position nixf::PositionRange::begin () const inline nodiscard
Definition at line 43 of file Range.h.
contains()
bool nixf::PositionRange::contains (const PositionRange & Pos) const inline nodiscard
Check if the range contains another range.
Definition at line 47 of file Range.h.
References PositionRange().
Referenced by nixf::LexerCursorRange::contains().
end()
Position nixf::PositionRange::end () const inline nodiscard
Definition at line 44 of file Range.h.
The documentation for this class was generated from the following file:
Range.h