nixd: nixf::Inherit Class Reference
nixf::Inherit Class Reference
#include <Attrs.h>
Public Member Functions
Inherit (LexerCursorRange Range, std::vector< std::shared_ptr< AttrName > > Names, std::shared_ptr< Expr > E)
const std::vector< std::shared_ptr< AttrName > > & names () const
bool hasExpr ()
const std::shared_ptr< Expr > & expr () const
ChildVector children () const override
Public Member Functions inherited from nixf::Node
NodeKind kind () const
LexerCursorRange range () const
PositionRange positionRange () const
LexerCursor lCur () const
LexerCursor rCur () const
const char * name () const
virtual ~Node ()=default
const Node * descend (PositionRange Range) const
Descendant node that contains the given range.
std::string_view src (std::string_view Src) const
Additional Inherited Members
Public Types inherited from nixf::Node
enum NodeKind { NK_BeginExpr , NK_EndExpr }
using ChildVector = boost::container::small_vector<Node *, 8>
Static Public Member Functions inherited from nixf::Node
static const char * name (NodeKind Kind)
Protected Member Functions inherited from nixf::Node
Node (NodeKind Kind, LexerCursorRange Range)
Detailed Description
Definition at line 145 of file Attrs.h.
Constructor & Destructor Documentation
Inherit()
nixf::Inherit::Inherit (LexerCursorRange Range, std::vector< std::shared_ptr< AttrName > > Names, std::shared_ptr< Expr > E) inline
Definition at line 150 of file Attrs.h.
References nixf::Node::Node().
Member Function Documentation
children()
ChildVector nixf::Inherit::children () const inline nodiscard override virtual
Implements nixf::Node.
Definition at line 162 of file Attrs.h.
expr()
const std::shared_ptr< Expr > & nixf::Inherit::expr () const inline nodiscard
Definition at line 160 of file Attrs.h.
Referenced by nixf::Sema::lowerInherit().
hasExpr()
bool nixf::Inherit::hasExpr () inline nodiscard
Definition at line 158 of file Attrs.h.
names()
const std::vector< std::shared_ptr< AttrName > > & nixf::Inherit::names () const inline nodiscard
Definition at line 154 of file Attrs.h.
Referenced by nixf::Sema::lowerInherit().
The documentation for this class was generated from the following file:
Attrs.h