nixd: lspserver::detail Namespace Reference
lspserver::detail Namespace Reference
Functions
const char * debugType (const char *Filename)
void logImpl (Logger::Level, const char *Fmt, const llvm::formatv_object_base &)
template<typename T>
T && wrap (T &&V)
decltype(fmt_consume(llvm::Error::success())) wrap (llvm::Error &&V)
template<typename... Ts>
void log (Logger::Level L, const char *Fmt, Ts &&...Vals)
llvm::Error error (std::error_code, std::string &&)
Function Documentation
debugType()
const char * lspserver::detail::debugType (const char * Filename)
Definition at line 48 of file Logger.cpp.
error()
llvm::Error lspserver::detail::error (std::error_code EC, std::string && Msg)
Definition at line 87 of file Logger.cpp.
Referenced by lspserver::error(), lspserver::error(), lspserver::error(), and lspserver::error().
log()
template<typename... Ts> void lspserver::detail::log (Logger::Level L, const char * Fmt, Ts &&... Vals)
Definition at line 38 of file Logger.h.
References logImpl(), and wrap().
Referenced by lspserver::elog(), lspserver::log(), and lspserver::vlog().
logImpl()
void lspserver::detail::logImpl (Logger::Level Level, const char * Fmt, const llvm::formatv_object_base & Message)
Definition at line 37 of file Logger.cpp.
References lspserver::Logger::log().
Referenced by log().
wrap() [1/2]
decltype(fmt_consume(llvm::Error::success())) lspserver::detail::wrap (llvm::Error && V) inline
Definition at line 34 of file Logger.h.
wrap() [2/2]
template<typename T> T && lspserver::detail::wrap (T && V)
Definition at line 33 of file Logger.h.
Referenced by lspserver::error(), lspserver::error(), and log().