nixd: nixbc Namespace Reference
nixbc Namespace Reference
Classes
struct FileHeader
struct NodeHeader
class Origin
class OriginPath
Typedefs
using NixInt = int64_t
using NixFloat = double
using PosInt = uint32_t
Enumerations
enum ExprKind : int32_t {
EK_Assert , EK_Attrs , EK_Call , EK_ConcatStrings ,
EK_Float , EK_If , EK_Int , EK_Lambda ,
EK_Let , EK_List , EK_OpAnd , EK_OpConcatLists ,
EK_OpEq , EK_OpHasAttr , EK_OpImpl , EK_OpNEq ,
EK_OpNot , EK_OpOr , EK_OpUpdate , EK_Path ,
EK_Pos , EK_Select , EK_String , EK_Var ,
EK_With
}
Functions
void readBytecode (std::string_view &Data, Origin &Obj)
void writeBytecode (std::ostream &OS, const Origin &O)
void readBytecode (std::string_view &Data, OriginPath &Obj)
void writeBytecode (std::ostream &OS, const OriginPath &O)
Typedef Documentation
NixFloat
using nixbc::NixFloat = double
Definition at line 8 of file Type.h.
NixInt
using nixbc::NixInt = int64_t
Definition at line 7 of file Type.h.
PosInt
using nixbc::PosInt = uint32_t
Definition at line 9 of file Type.h.
Enumeration Type Documentation
ExprKind
enum nixbc::ExprKind : int32_t
Enumerator
EK_Assert
EK_Attrs
EK_Call
EK_ConcatStrings
EK_Float
EK_If
EK_Int
EK_Lambda
EK_Let
EK_List
EK_OpAnd
EK_OpConcatLists
EK_OpEq
EK_OpHasAttr
EK_OpImpl
EK_OpNEq
EK_OpNot
EK_OpOr
EK_OpUpdate
EK_Path
EK_Pos
EK_Select
EK_String
EK_Var
EK_With
Definition at line 7 of file libnixbc/include/nixbc/Nodes.h.
Function Documentation
readBytecode() [1/2]
void nixbc::readBytecode (std::string_view & Data, Origin & Obj)
Definition at line 7 of file Origin.cpp.
readBytecode() [2/2]
void nixbc::readBytecode (std::string_view & Data, OriginPath & Obj)
Definition at line 11 of file Origin.cpp.
writeBytecode() [1/2]
void nixbc::writeBytecode (std::ostream & OS, const Origin & O)
Definition at line 9 of file Origin.cpp.
Referenced by nixf::writeBytecode(), nixf::writeBytecode(), and nixf::writeBytecode().
writeBytecode() [2/2]
void nixbc::writeBytecode (std::ostream & OS, const OriginPath & O)
Definition at line 13 of file Origin.cpp.