nixd: lspserver Namespace Reference
lspserver Namespace Reference
Whether current platform treats paths case insensitively.
Namespaces
namespace detail
Classes
struct ApplyWorkspaceEditParams
struct ApplyWorkspaceEditResponse
struct ASTNode
struct ASTParams
struct CallHierarchyIncomingCall
Represents an incoming call, e.g. a caller of a method or constructor.
struct CallHierarchyIncomingCallsParams
The parameter of a callHierarchy/incomingCalls request.
struct CallHierarchyItem
struct CallHierarchyOutgoingCall
struct CallHierarchyOutgoingCallsParams
The parameter of a callHierarchy/outgoingCalls request.
struct CallHierarchyPrepareParams
The parameter of a textDocument/prepareCallHierarchy request.
struct ChangeAnnotation
struct ClangdCompileCommand
struct ClientCapabilities
struct CodeAction
struct CodeActionContext
struct CodeActionParams
struct CodeDescription
Structure to capture a description for an error code.
struct Command
struct CompletionContext
struct CompletionItem
struct CompletionList
Represents a collection of completion items to be presented in the editor.
struct CompletionParams
struct ConfigurationItem
struct ConfigurationParams
struct ConfigurationSettings
struct Diagnostic
struct DiagnosticRelatedInformation
struct DidChangeConfigurationParams
struct DidChangeTextDocumentParams
struct DidChangeWatchedFilesParams
struct DidCloseTextDocumentParams
struct DidOpenTextDocumentParams
struct DidSaveTextDocumentParams
struct DocumentFormattingParams
struct DocumentHighlight
struct DocumentLink
struct DocumentLinkParams
Parameters for the document link request.
struct DocumentOnTypeFormattingParams
struct DocumentRangeFormattingParams
struct DocumentSymbol
struct DocumentSymbolParams
class DraftStore
class Event
An Event<T> allows events of type T to be broadcast to listeners.
struct ExecuteCommandParams
struct FileEvent
struct FileStatus
struct FoldingRange
Stores information about a region of code that can be folded.
struct FoldingRangeParams
struct HandlerRegistry
struct Hover
struct InactiveRegionsParams
class InboundPort
struct InitializationOptions
struct InitializeParams
struct InlayHint
Inlay hint information.
struct InlayHintsParams
A parameter literal used in inlay hint requests.
class Key
struct Location
class Logger
Interface to allow custom logging in clangd.
class LoggingSession
Only one LoggingSession can be active at a time.
struct LSPDiagnosticCompare
class LSPError
class LSPServer
struct MarkupContent
class MessageHandler
struct NoParams
class OutboundPort
struct ParameterInformation
A single parameter of a particular signature.
struct Position
struct ProgressParams
struct PublishDiagnosticsParams
struct Range
struct ReferenceContext
struct ReferenceLocation
struct ReferenceParams
struct RenameParams
struct ResolveTypeHierarchyItemParams
Parameters for the typeHierarchy/resolve request.
struct SelectionRange
struct SelectionRangeParams
struct SemanticToken
struct SemanticTokens
A versioned set of tokens.
struct SemanticTokensDeltaParams
struct SemanticTokensEdit
Describes a replacement of a contiguous range of semanticTokens.
struct SemanticTokensOrDelta
struct SemanticTokensParams
Body of textDocument/semanticTokens/full request.
struct ShowMessageParams
struct SignatureHelp
Represents the signature of a callable.
struct SignatureInformation
Represents the signature of something callable.
class StreamLogger
struct SymbolInformation
struct TextDocumentContentChangeEvent
struct TextDocumentEdit
struct TextDocumentIdentifier
struct TextDocumentItem
struct TextDocumentPositionParams
struct TextEdit
struct TweakArgs
struct TypeHierarchyItem
struct TypeHierarchyPrepareParams
class URI
struct URIForFile
class URIScheme
struct VersionedTextDocumentIdentifier
struct WorkDoneProgressBegin
struct WorkDoneProgressCreateParams
struct WorkDoneProgressEnd
Signals the end of progress reporting.
struct WorkDoneProgressReport
Reporting progress is done using the following payload.
struct WorkspaceEdit
struct WorkspaceSymbolParams
The parameters of a Workspace Symbol Request.
Typedefs
template<typename T>
using Callback = llvm::unique_function<void(llvm::Expected<T>)>
using Path = std::string
using PathRef = llvm::StringRef
using ChangeAnnotationIdentifier = std::string
using InitializedParams = NoParams
using CompletionItemKindBitset = std::bitset<CompletionItemKindMax + 1>
using SymbolKindBitset = std::bitset<SymbolKindMax + 1>
typedef llvm::Registry< URIScheme > URISchemeRegistry
Enumerations
enum class JSONStreamStyle { Standard , LitTest }
enum class ErrorCode {
ParseError = -32700 , InvalidRequest = -32600 , MethodNotFound = -32601 , InvalidParams = -32602 ,
InternalError = -32603 , ServerNotInitialized = -32002 , UnknownErrorCode = -32001 , RequestCancelled = -32800 ,
ContentModified = -32801
}
enum class TraceLevel { Off = 0 , Messages = 1 , Verbose = 2 }
enum class TextDocumentSyncKind { None = 0 , Full = 1 , Incremental = 2 }
enum class CompletionItemKind {
Missing = 0 , Text = 1 , Method = 2 , Function = 3 ,
Constructor = 4 , Field = 5 , Variable = 6 , Class = 7 ,
Interface = 8 , Module = 9 , Property = 10 , Unit = 11 ,
Value = 12 , Enum = 13 , Keyword = 14 , Snippet = 15 ,
Color = 16 , File = 17 , Reference = 18 , Folder = 19 ,
EnumMember = 20 , Constant = 21 , Struct = 22 , Event = 23 ,
Operator = 24 , TypeParameter = 25
}
The kind of a completion entry.
enum class SymbolKind {
File = 1 , Module = 2 , Namespace = 3 , Package = 4 ,
Class = 5 , Method = 6 , Property = 7 , Field = 8 ,
Constructor = 9 , Enum = 10 , Interface = 11 , Function = 12 ,
Variable = 13 , Constant = 14 , String = 15 , Number = 16 ,
Boolean = 17 , Array = 18 , Object = 19 , Key = 20 ,
Null = 21 , EnumMember = 22 , Struct = 23 , Event = 24 ,
Operator = 25 , TypeParameter = 26
}
A symbol kind.
enum class OffsetEncoding { UnsupportedEncoding , UTF16 , UTF8 , UTF32 }
enum class MarkupKind { PlainText , Markdown }
enum class MessageType { Error = 1 , Warning = 2 , Info = 3 , Log = 4 }
enum class FileChangeType { Created = 1 , Changed = 2 , Deleted = 3 }
enum DiagnosticTag { Unnecessary = 1 , Deprecated = 2 }
enum class CompletionTriggerKind { Invoked = 1 , TriggerCharacter = 2 , TriggerTriggerForIncompleteCompletions = 3 }
enum class InsertTextFormat { Missing = 0 , PlainText = 1 , Snippet = 2 }
enum class DocumentHighlightKind { Text = 1 , Read = 2 , Write = 3 }
enum class TypeHierarchyDirection { Children = 0 , Parents = 1 , Both = 2 }
enum class SymbolTag { Deprecated = 1 }
enum class InlayHintKind { Type = 1 , Parameter = 2 , Designator = 3 }
Inlay hint kinds.
Functions
template<typename... Ts>
void elog (const char *Fmt, Ts &&...Vals)
template<typename... Ts>
void log (const char *Fmt, Ts &&...Vals)
template<typename... Ts>
void vlog (const char *Fmt, Ts &&...Vals)
template<typename... Ts>
llvm::Error error (std::error_code EC, const char *Fmt, Ts &&...Vals)
template<typename... Ts>
llvm::Error error (const char *Fmt, Ts &&...Vals)
llvm::Error error (std::error_code EC, std::string Msg)
llvm::Error error (std::string Msg)
template<typename T>
llvm::Expected< T > parseParam (const llvm::json::Value &Raw, llvm::StringRef PayloadName, llvm::StringRef PayloadKind)
template<>
llvm::Expected< llvm::json::Value > parseParam (const llvm::json::Value &Raw, llvm::StringRef PayloadName, llvm::StringRef PayloadKind)
std::string maybeCaseFoldPath (PathRef Path)
bool pathEqual (PathRef, PathRef)
bool pathStartsWith (PathRef Ancestor, PathRef Path, llvm::sys::path::Style Style=llvm::sys::path::Style::native)
PathRef absoluteParent (PathRef Path)
llvm::json::Value toJSON (const URIForFile &U)
Serialize/deserialize URIForFile to/from a string URI.
bool fromJSON (const llvm::json::Value &, URIForFile &, llvm::json::Path)
llvm::json::Value toJSON (const TextDocumentIdentifier &)
bool fromJSON (const llvm::json::Value &, TextDocumentIdentifier &, llvm::json::Path)
llvm::json::Value toJSON (const VersionedTextDocumentIdentifier &)
bool fromJSON (const llvm::json::Value &, VersionedTextDocumentIdentifier &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, Position &, llvm::json::Path)
llvm::json::Value toJSON (const Position &)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const Position &)
bool fromJSON (const llvm::json::Value &, Range &, llvm::json::Path)
llvm::json::Value toJSON (const Range &)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const Range &)
llvm::json::Value toJSON (const Location &)
bool fromJSON (const llvm::json::Value &, Location &, llvm::json::Path)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const Location &)
llvm::json::Value toJSON (const ReferenceLocation &)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const ReferenceLocation &)
bool operator== (const TextEdit &L, const TextEdit &R)
bool fromJSON (const llvm::json::Value &, TextEdit &, llvm::json::Path)
llvm::json::Value toJSON (const TextEdit &)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const TextEdit &)
bool fromJSON (const llvm::json::Value &, ChangeAnnotation &, llvm::json::Path)
llvm::json::Value toJSON (const ChangeAnnotation &)
bool fromJSON (const llvm::json::Value &, TextDocumentEdit &, llvm::json::Path)
llvm::json::Value toJSON (const TextDocumentEdit &)
bool fromJSON (const llvm::json::Value &, TextDocumentItem &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &E, TraceLevel &Out, llvm::json::Path)
llvm::json::Value toJSON (const NoParams &)
bool fromJSON (const llvm::json::Value &, NoParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, CompletionItemKind &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, CompletionItemKindBitset &, llvm::json::Path)
CompletionItemKind adjustKindToCapability (CompletionItemKind Kind, CompletionItemKindBitset &SupportedCompletionItemKinds)
bool fromJSON (const llvm::json::Value &, SymbolKind &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, SymbolKindBitset &, llvm::json::Path)
SymbolKind adjustKindToCapability (SymbolKind Kind, SymbolKindBitset &supportedSymbolKinds)
llvm::json::Value toJSON (const OffsetEncoding &)
bool fromJSON (const llvm::json::Value &, OffsetEncoding &, llvm::json::Path)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, OffsetEncoding)
bool fromJSON (const llvm::json::Value &, MarkupKind &, llvm::json::Path)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, MarkupKind)
bool fromJSON (const llvm::json::Value &, ClientCapabilities &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, ClangdCompileCommand &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, ConfigurationSettings &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, InitializationOptions &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, InitializeParams &, llvm::json::Path)
llvm::json::Value toJSON (const WorkDoneProgressCreateParams &P)
template<typename T>
llvm::json::Value toJSON (const ProgressParams< T > &P)
llvm::json::Value toJSON (const WorkDoneProgressBegin &)
llvm::json::Value toJSON (const WorkDoneProgressReport &)
llvm::json::Value toJSON (const WorkDoneProgressEnd &)
llvm::json::Value toJSON (const MessageType &)
llvm::json::Value toJSON (const ShowMessageParams &)
bool fromJSON (const llvm::json::Value &, DidOpenTextDocumentParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, DidCloseTextDocumentParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, DidSaveTextDocumentParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, TextDocumentContentChangeEvent &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, DidChangeTextDocumentParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &E, FileChangeType &Out, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, FileEvent &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, DidChangeWatchedFilesParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, DidChangeConfigurationParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, DocumentRangeFormattingParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, DocumentOnTypeFormattingParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, DocumentFormattingParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, DocumentSymbolParams &, llvm::json::Path)
llvm::json::Value toJSON (const DiagnosticRelatedInformation &)
llvm::json::Value toJSON (DiagnosticTag Tag)
llvm::json::Value toJSON (const CodeDescription &)
llvm::json::Value toJSON (const Diagnostic &)
bool fromJSON (const llvm::json::Value &, Diagnostic &, llvm::json::Path)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const Diagnostic &)
llvm::json::Value toJSON (const PublishDiagnosticsParams &)
bool fromJSON (const llvm::json::Value &, CodeActionContext &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, CodeActionParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, WorkspaceEdit &, llvm::json::Path)
llvm::json::Value toJSON (const WorkspaceEdit &WE)
bool fromJSON (const llvm::json::Value &, TweakArgs &, llvm::json::Path)
llvm::json::Value toJSON (const TweakArgs &A)
bool fromJSON (const llvm::json::Value &, ExecuteCommandParams &, llvm::json::Path)
llvm::json::Value toJSON (const Command &C)
llvm::json::Value toJSON (const CodeAction &)
llvm::raw_ostream & operator<< (llvm::raw_ostream &O, const DocumentSymbol &S)
llvm::json::Value toJSON (const DocumentSymbol &S)
llvm::json::Value toJSON (const SymbolInformation &)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const SymbolInformation &)
bool fromJSON (const llvm::json::Value &, WorkspaceSymbolParams &, llvm::json::Path)
llvm::json::Value toJSON (const ApplyWorkspaceEditParams &)
bool fromJSON (const llvm::json::Value &, ApplyWorkspaceEditResponse &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, TextDocumentPositionParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, CompletionContext &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, CompletionParams &, llvm::json::Path)
llvm::json::Value toJSON (const MarkupContent &MC)
bool fromJSON (const llvm::json::Value &, MarkupContent &, llvm::json::Path)
llvm::json::Value toJSON (const Hover &H)
llvm::json::Value toJSON (const CompletionItem &)
bool fromJSON (const llvm::json::Value &, CompletionItem &, llvm::json::Path)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const CompletionItem &)
bool operator< (const CompletionItem &, const CompletionItem &)
llvm::json::Value toJSON (const CompletionList &)
llvm::json::Value toJSON (const ParameterInformation &)
llvm::json::Value toJSON (const SignatureInformation &)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const SignatureInformation &)
llvm::json::Value toJSON (const SignatureHelp &)
bool fromJSON (const llvm::json::Value &, RenameParams &, llvm::json::Path)
llvm::json::Value toJSON (const DocumentHighlight &DH)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const DocumentHighlight &)
bool fromJSON (const llvm::json::Value &E, TypeHierarchyDirection &Out, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, TypeHierarchyPrepareParams &, llvm::json::Path)
llvm::json::Value toJSON (const TypeHierarchyItem::ResolveParams &)
bool fromJSON (const TypeHierarchyItem::ResolveParams &)
llvm::json::Value toJSON (const TypeHierarchyItem &)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const TypeHierarchyItem &)
bool fromJSON (const llvm::json::Value &, TypeHierarchyItem &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, ResolveTypeHierarchyItemParams &, llvm::json::Path)
llvm::json::Value toJSON (SymbolTag)
llvm::json::Value toJSON (const CallHierarchyItem &)
bool fromJSON (const llvm::json::Value &, CallHierarchyItem &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &, CallHierarchyIncomingCallsParams &, llvm::json::Path)
llvm::json::Value toJSON (const CallHierarchyIncomingCall &)
bool fromJSON (const llvm::json::Value &, CallHierarchyOutgoingCallsParams &, llvm::json::Path)
llvm::json::Value toJSON (const CallHierarchyOutgoingCall &)
bool fromJSON (const llvm::json::Value &, InlayHintsParams &, llvm::json::Path)
llvm::json::Value toJSON (const InlayHintKind &)
llvm::json::Value toJSON (const InlayHint &)
bool operator== (const InlayHint &, const InlayHint &)
bool operator< (const InlayHint &, const InlayHint &)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, InlayHintKind)
bool fromJSON (const llvm::json::Value &, ReferenceParams &, llvm::json::Path)
llvm::json::Value toJSON (const FileStatus &)
bool operator== (const SemanticToken &, const SemanticToken &)
llvm::json::Value toJSON (const SemanticTokens &)
bool fromJSON (const llvm::json::Value &, SemanticTokensParams &, llvm::json::Path)
bool fromJSON (const llvm::json::Value &Params, SemanticTokensDeltaParams &R, llvm::json::Path)
llvm::json::Value toJSON (const SemanticTokensEdit &)
llvm::json::Value toJSON (const SemanticTokensOrDelta &)
llvm::json::Value toJSON (const InactiveRegionsParams &InactiveRegions)
bool fromJSON (const llvm::json::Value &, SelectionRangeParams &, llvm::json::Path)
llvm::json::Value toJSON (const SelectionRange &)
bool fromJSON (const llvm::json::Value &, DocumentLinkParams &, llvm::json::Path)
llvm::json::Value toJSON (const DocumentLink &DocumentLink)
bool fromJSON (const llvm::json::Value &, FoldingRangeParams &, llvm::json::Path)
llvm::json::Value toJSON (const FoldingRange &Range)
bool fromJSON (const llvm::json::Value &, ASTParams &, llvm::json::Path)
llvm::json::Value toJSON (const ASTNode &)
llvm::raw_ostream & operator<< (llvm::raw_ostream &, const ASTNode &)
llvm::json::Value toJSON (const ConfigurationItem &)
llvm::json::Value toJSON (const ConfigurationParams &)
size_t lspLength (llvm::StringRef Code)
llvm::Expected< size_t > positionToOffset (llvm::StringRef Code, Position P, bool AllowColumnsBeyondLineLength=true)
Position offsetToPosition (llvm::StringRef Code, size_t Offset)
void unionRanges (Range &A, Range B)
llvm::Error applyChange (std::string &Contents, const TextDocumentContentChangeEvent &Change)
Apply an incremental update to a text document.
llvm::StringSet collectWords (llvm::StringRef Content)
llvm::Error decodeError (const llvm::json::Object &O)
Decode the given JSON object into an error.
bool readLine (int fd, const std::atomic< bool > &Close, llvm::SmallString< 128 > &Line)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const URIForFile &U)
bool fromJSON (const llvm::json::Value &Params, TypeHierarchyItem::ResolveParams &RP, llvm::json::Path P)
bool fromJSON (const llvm::json::Value &Params, ReferenceContext &R, llvm::json::Path P)
Variables
constexpr auto CompletionItemKindMin
constexpr auto CompletionItemKindMax
constexpr auto SymbolKindMin = static_cast<size_t>(SymbolKind::File)
constexpr auto SymbolKindMax = static_cast<size_t>(SymbolKind::TypeParameter)
Key< OffsetEncoding > kCurrentOffsetEncoding
constexpr unsigned SemanticTokenEncodingSize = 5
Detailed Description
Whether current platform treats paths case insensitively.
Typedef Documentation
Callback
template<typename T> using lspserver::Callback = llvm::unique_function<void(llvm::Expected<T>)>
A Callback<T> is a void function that accepts Expected<T>. This is accepted by ClangdServer functions that logically return T.
Definition at line 14 of file Function.h.
ChangeAnnotationIdentifier
using lspserver::ChangeAnnotationIdentifier = std::string
Definition at line 223 of file lspserver/include/lspserver/Protocol.h.
CompletionItemKindBitset
using lspserver::CompletionItemKindBitset = std::bitset<CompletionItemKindMax + 1>
Definition at line 354 of file lspserver/include/lspserver/Protocol.h.
InitializedParams
using lspserver::InitializedParams = NoParams
Definition at line 303 of file lspserver/include/lspserver/Protocol.h.
Path
using lspserver::Path = std::string
A typedef to represent a file path. Used solely for more descriptive signatures.
Definition at line 24 of file Path.h.
PathRef
using lspserver::PathRef = llvm::StringRef
A typedef to represent a ref to file path. Used solely for more descriptive signatures.
Definition at line 27 of file Path.h.
SymbolKindBitset
using lspserver::SymbolKindBitset = std::bitset<SymbolKindMax + 1>
Definition at line 393 of file lspserver/include/lspserver/Protocol.h.
URISchemeRegistry
typedef llvm::Registry<URIScheme> lspserver::URISchemeRegistry
By default, a "file" scheme is supported where URI paths are always absolute in the file system.
Definition at line 121 of file URI.h.
Enumeration Type Documentation
CompletionItemKind
enum class lspserver::CompletionItemKind strong
The kind of a completion entry.
Enumerator
Missing
Text
Method
Function
Constructor
Field
Variable
Class
Interface
Module
Property
Unit
Value
Enum
Keyword
Snippet
Color
File
Reference
Folder
EnumMember
Constant
Struct
Event
Operator
TypeParameter
Definition at line 320 of file lspserver/include/lspserver/Protocol.h.
CompletionTriggerKind
enum class lspserver::CompletionTriggerKind strong
Enumerator
Invoked
Completion was triggered by typing an identifier (24x7 code complete), manual invocation (e.g Ctrl+Space) or via API.
TriggerCharacter
Completion was triggered by a trigger character specified by the triggerCharacters properties of the CompletionRegistrationOptions.
TriggerTriggerForIncompleteCompletions
Completion was re-triggered as the current completion list is incomplete.
Definition at line 1171 of file lspserver/include/lspserver/Protocol.h.
DiagnosticTag
enum lspserver::DiagnosticTag
Enumerator
Unnecessary
Unused or unnecessary code.
Clients are allowed to render diagnostics with this tag faded out instead of having an error squiggle.
Deprecated
Deprecated or obsolete code.
Clients are allowed to rendered diagnostics with this tag strike through.
Definition at line 870 of file lspserver/include/lspserver/Protocol.h.
DocumentHighlightKind
enum class lspserver::DocumentHighlightKind strong
Enumerator
Text
Read
Write
Definition at line 1381 of file lspserver/include/lspserver/Protocol.h.
ErrorCode
enum class lspserver::ErrorCode strong
Enumerator
ParseError
InvalidRequest
MethodNotFound
InvalidParams
InternalError
ServerNotInitialized
UnknownErrorCode
RequestCancelled
ContentModified
Definition at line 22 of file lspserver/include/lspserver/Protocol.h.
FileChangeType
enum class lspserver::FileChangeType strong
Enumerator
Created
The file got created.
Changed
The file got changed.
Deleted
The file got deleted.
Definition at line 782 of file lspserver/include/lspserver/Protocol.h.
InlayHintKind
enum class lspserver::InlayHintKind strong
Inlay hint kinds.
Enumerator
Type
An inlay hint that for a type annotation.
An example of a type hint is a hint in this position: auto var ^ = expr; which shows the deduced type of the variable.
Parameter
An inlay hint that is for a parameter.
An example of a parameter hint is a hint in this position: func(^arg); which shows the name of the corresponding parameter.
Designator
A hint before an element of an aggregate braced initializer list, indicating what it is initializing. Pair{^1, ^2}; Uses designator syntax, e.g. .first:. This is a clangd extension.
Definition at line 1584 of file lspserver/include/lspserver/Protocol.h.
InsertTextFormat
enum class lspserver::InsertTextFormat strong
Defines whether the insert text in a completion item should be interpreted as plain text or a snippet.
Enumerator
Missing
PlainText
The primary text to be inserted is treated as a plain string.
Snippet
The primary text to be inserted is treated as a snippet.
A snippet can define tab stops and placeholders with $1, $2 and ${3:foo}. $0 defines the final tab stop, it defaults to the end of the snippet. Placeholders with equal identifiers are linked, that is typing in one will update others too.
See also: https://github.com/Microsoft/vscode/blob/main/src/vs/editor/contrib/snippet/snippet.md
Definition at line 1219 of file lspserver/include/lspserver/Protocol.h.
JSONStreamStyle
enum class lspserver::JSONStreamStyle strong
Enumerator
Standard
LitTest
Definition at line 13 of file Connection.h.
MarkupKind
enum class lspserver::MarkupKind strong
Enumerator
PlainText
Markdown
Definition at line 415 of file lspserver/include/lspserver/Protocol.h.
MessageType
enum class lspserver::MessageType strong
Enumerator
Error
An error message.
Warning
A warning message.
Info
An information message.
Log
A log message.
Definition at line 702 of file lspserver/include/lspserver/Protocol.h.
OffsetEncoding
enum class lspserver::OffsetEncoding strong
Enumerator
UnsupportedEncoding
UTF16
UTF8
UTF32
Definition at line 399 of file lspserver/include/lspserver/Protocol.h.
SymbolKind
enum class lspserver::SymbolKind strong
A symbol kind.
Enumerator
File
Module
Namespace
Package
Class
Method
Property
Field
Constructor
Enum
Interface
Function
Variable
Constant
String
Number
Boolean
Array
Object
Key
Null
EnumMember
Struct
Event
Operator
TypeParameter
Definition at line 362 of file lspserver/include/lspserver/Protocol.h.
SymbolTag
enum class lspserver::SymbolTag strong
Enumerator
Deprecated
Definition at line 1493 of file lspserver/include/lspserver/Protocol.h.
TextDocumentSyncKind
enum class lspserver::TextDocumentSyncKind strong
Defines how the host (editor) should sync document changes to the language server.
Enumerator
None
Documents should not be synced at all.
Full
Documents are synced by always sending the full content of the document.
Incremental
Documents are synced by sending the full content on open. After that only incremental updates to the document are send.
Definition at line 307 of file lspserver/include/lspserver/Protocol.h.
TraceLevel
enum class lspserver::TraceLevel strong
Enumerator
Off
Messages
Verbose
Definition at line 291 of file lspserver/include/lspserver/Protocol.h.
TypeHierarchyDirection
enum class lspserver::TypeHierarchyDirection strong
Enumerator
Children
Parents
Both
Definition at line 1409 of file lspserver/include/lspserver/Protocol.h.
Function Documentation
absoluteParent()
PathRef lspserver::absoluteParent (PathRef Path)
Variant of parent_path that operates only on absolute paths. Unlike parent_path doesn't consider C: a parent of C:.
adjustKindToCapability() [1/2]
CompletionItemKind lspserver::adjustKindToCapability (CompletionItemKind Kind, CompletionItemKindBitset & SupportedCompletionItemKinds)
Definition at line 956 of file lspserver/src/Protocol.cpp.
References Class, CompletionItemKindMin, Enum, EnumMember, File, Folder, Struct, and Text.
adjustKindToCapability() [2/2]
SymbolKind lspserver::adjustKindToCapability (SymbolKind Kind, SymbolKindBitset & supportedSymbolKinds)
Definition at line 283 of file lspserver/src/Protocol.cpp.
References Class, Enum, EnumMember, String, Struct, and SymbolKindMin.
applyChange()
llvm::Error lspserver::applyChange (std::string & Contents, const TextDocumentContentChangeEvent & Change)
Apply an incremental update to a text document.
Definition at line 191 of file SourceCode.cpp.
References error(), lspLength(), positionToOffset(), lspserver::TextDocumentContentChangeEvent::range, lspserver::TextDocumentContentChangeEvent::rangeLength, and lspserver::TextDocumentContentChangeEvent::text.
collectWords()
llvm::StringSet lspserver::collectWords (llvm::StringRef Content)
Collects words from the source code. Unlike collectIdentifiers:
also finds text in comments:
splits text into words
drops stopwords like "get" and "for"
decodeError()
llvm::Error lspserver::decodeError (const llvm::json::Object & O)
Decode the given JSON object into an error.
Definition at line 71 of file Connection.cpp.
Referenced by lspserver::InboundPort::dispatch().
elog()
template<typename... Ts> void lspserver::elog (const char * Fmt, Ts &&... Vals)
Definition at line 52 of file Logger.h.
References lspserver::Logger::Error, and lspserver::detail::log().
Referenced by lspserver::URIForFile::canonicalize(), lspserver::DraftStore::decodeVersion(), lspserver::InboundPort::dispatch(), lspserver::InboundPort::loop(), parseParam(), and lspserver::InboundPort::readStandardMessage().
error() [1/4]
template<typename... Ts> llvm::Error lspserver::error (const char * Fmt, Ts &&... Vals)
Definition at line 76 of file Logger.h.
References lspserver::detail::error(), and lspserver::detail::wrap().
error() [2/4]
template<typename... Ts> llvm::Error lspserver::error (std::error_code EC, const char * Fmt, Ts &&... Vals)
Definition at line 70 of file Logger.h.
References lspserver::detail::error(), and lspserver::detail::wrap().
Referenced by applyChange(), lspserver::URI::create(), nixd::AttrSetProvider::onAttrPathComplete(), nixd::AttrSetProvider::onAttrPathInfo(), nixd::AttrSetProvider::onEvalExpr(), nixd::AttrSetProvider::onOptionComplete(), nixd::AttrSetProvider::onOptionInfo(), lspserver::URI::parse(), and positionToOffset().
error() [3/4]
llvm::Error lspserver::error (std::error_code EC, std::string Msg) inline
Definition at line 82 of file Logger.h.
References lspserver::detail::error().
error() [4/4]
llvm::Error lspserver::error (std::string Msg) inline
Definition at line 86 of file Logger.h.
References lspserver::detail::error().
fromJSON() [1/68]
bool lspserver::fromJSON (const llvm::json::Value & Response, ApplyWorkspaceEditResponse & R, llvm::json::Path P)
Definition at line 841 of file lspserver/src/Protocol.cpp.
References lspserver::ApplyWorkspaceEditResponse::applied, and lspserver::ApplyWorkspaceEditResponse::failureReason.
fromJSON() [2/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, ASTParams & R, llvm::json::Path P)
Definition at line 1501 of file lspserver/src/Protocol.cpp.
References lspserver::ASTParams::range, and lspserver::ASTParams::textDocument.
fromJSON() [3/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, CallHierarchyIncomingCallsParams & C, llvm::json::Path P)
Definition at line 1347 of file lspserver/src/Protocol.cpp.
References lspserver::CallHierarchyIncomingCallsParams::item.
fromJSON() [4/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, CallHierarchyItem & I, llvm::json::Path P)
Definition at line 1334 of file lspserver/src/Protocol.cpp.
References lspserver::CallHierarchyItem::data, lspserver::CallHierarchyItem::kind, lspserver::CallHierarchyItem::name, lspserver::CallHierarchyItem::range, lspserver::CallHierarchyItem::selectionRange, and lspserver::CallHierarchyItem::uri.
fromJSON() [5/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, CallHierarchyOutgoingCallsParams & C, llvm::json::Path P)
Definition at line 1357 of file lspserver/src/Protocol.cpp.
References lspserver::CallHierarchyOutgoingCallsParams::item.
fromJSON() [6/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, ChangeAnnotation & R, llvm::json::Path P)
Definition at line 208 of file lspserver/src/Protocol.cpp.
References lspserver::ChangeAnnotation::description, lspserver::ChangeAnnotation::label, and lspserver::ChangeAnnotation::needsConfirmation.
fromJSON() [7/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, ClangdCompileCommand & CDbUpdate, llvm::json::Path P)
Definition at line 1201 of file lspserver/src/Protocol.cpp.
References lspserver::ClangdCompileCommand::compilationCommand, and lspserver::ClangdCompileCommand::workingDirectory.
fromJSON() [8/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, ClientCapabilities & R, llvm::json::Path P)
Definition at line 301 of file lspserver/src/Protocol.cpp.
References lspserver::ClientCapabilities::CancelsStaleRequests, lspserver::ClientCapabilities::ChangeAnnotation, lspserver::ClientCapabilities::CodeActionStructure, lspserver::ClientCapabilities::CompletionDocumentationFormat, lspserver::ClientCapabilities::CompletionFixes, lspserver::ClientCapabilities::CompletionItemKinds, lspserver::ClientCapabilities::CompletionSnippets, lspserver::ClientCapabilities::DiagnosticCategory, lspserver::ClientCapabilities::DiagnosticFixes, lspserver::ClientCapabilities::DiagnosticRelatedInformation, lspserver::ClientCapabilities::DocumentChanges, fromJSON(), lspserver::ClientCapabilities::HasSignatureHelp, lspserver::ClientCapabilities::HierarchicalDocumentSymbol, lspserver::ClientCapabilities::HoverContentFormat, lspserver::ClientCapabilities::ImplicitProgressCreation, lspserver::ClientCapabilities::InactiveRegions, Info, lspserver::ClientCapabilities::LineFoldingOnly, lspserver::ClientCapabilities::offsetEncoding, lspserver::ClientCapabilities::OffsetsInSignatureHelp, Parameter, lspserver::ClientCapabilities::ReferenceContainer, lspserver::ClientCapabilities::RenamePrepareSupport, lspserver::ClientCapabilities::SemanticTokenRefreshSupport, lspserver::ClientCapabilities::SemanticTokens, lspserver::ClientCapabilities::SignatureHelpDocumentationFormat, lspserver::ClientCapabilities::TheiaSemanticHighlighting, lspserver::ClientCapabilities::WorkDoneProgress, lspserver::ClientCapabilities::WorkspaceConfiguration, and lspserver::ClientCapabilities::WorkspaceSymbolKinds.
fromJSON() [9/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, CodeActionContext & R, llvm::json::Path P)
Definition at line 665 of file lspserver/src/Protocol.cpp.
References lspserver::CodeActionContext::diagnostics, and lspserver::CodeActionContext::only.
fromJSON() [10/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, CodeActionParams & R, llvm::json::Path P)
Definition at line 696 of file lspserver/src/Protocol.cpp.
References lspserver::CodeActionParams::context, lspserver::CodeActionParams::range, and lspserver::CodeActionParams::textDocument.
fromJSON() [11/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, CompletionContext & R, llvm::json::Path P)
Definition at line 855 of file lspserver/src/Protocol.cpp.
References lspserver::CompletionContext::triggerCharacter, and lspserver::CompletionContext::triggerKind.
fromJSON() [12/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, CompletionItem & R, llvm::json::Path P)
Definition at line 1018 of file lspserver/src/Protocol.cpp.
References lspserver::CompletionItem::additionalTextEdits, lspserver::CompletionItem::data, lspserver::CompletionItem::detail, lspserver::CompletionItem::documentation, lspserver::CompletionItem::filterText, lspserver::CompletionItem::insertText, lspserver::CompletionItem::insertTextFormat, lspserver::CompletionItem::kind, lspserver::CompletionItem::label, lspserver::CompletionItem::sortText, and lspserver::CompletionItem::textEdit.
fromJSON() [13/68]
bool lspserver::fromJSON (const llvm::json::Value & E, CompletionItemKind & Out, llvm::json::Path P)
Definition at line 943 of file lspserver/src/Protocol.cpp.
References Text, and TypeParameter.
fromJSON() [14/68]
bool lspserver::fromJSON (const llvm::json::Value & E, CompletionItemKindBitset & Out, llvm::json::Path P)
Definition at line 977 of file lspserver/src/Protocol.cpp.
References fromJSON().
fromJSON() [15/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, CompletionParams & R, llvm::json::Path P)
Definition at line 866 of file lspserver/src/Protocol.cpp.
References lspserver::CompletionParams::context, fromJSON(), and lspserver::CompletionParams::limit.
fromJSON() [16/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, ConfigurationSettings & S, llvm::json::Path P)
Definition at line 1208 of file lspserver/src/Protocol.cpp.
References lspserver::ConfigurationSettings::compilationDatabaseChanges.
fromJSON() [17/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, Diagnostic & R, llvm::json::Path P)
Definition at line 641 of file lspserver/src/Protocol.cpp.
References lspserver::Diagnostic::category, lspserver::Diagnostic::code, lspserver::Diagnostic::data, lspserver::Diagnostic::message, lspserver::Diagnostic::range, lspserver::Diagnostic::severity, and lspserver::Diagnostic::source.
fromJSON() [18/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, DidChangeConfigurationParams & CCP, llvm::json::Path P)
Definition at line 1195 of file lspserver/src/Protocol.cpp.
References lspserver::DidChangeConfigurationParams::settings.
fromJSON() [19/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, DidChangeTextDocumentParams & R, llvm::json::Path P)
Definition at line 537 of file lspserver/src/Protocol.cpp.
References lspserver::DidChangeTextDocumentParams::contentChanges, lspserver::DidChangeTextDocumentParams::forceRebuild, lspserver::DidChangeTextDocumentParams::textDocument, and lspserver::DidChangeTextDocumentParams::wantDiagnostics.
fromJSON() [20/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, DidChangeWatchedFilesParams & R, llvm::json::Path P)
Definition at line 564 of file lspserver/src/Protocol.cpp.
References lspserver::DidChangeWatchedFilesParams::changes.
fromJSON() [21/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, DidCloseTextDocumentParams & R, llvm::json::Path P)
Definition at line 525 of file lspserver/src/Protocol.cpp.
References lspserver::DidCloseTextDocumentParams::textDocument.
fromJSON() [22/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, DidOpenTextDocumentParams & R, llvm::json::Path P)
Definition at line 519 of file lspserver/src/Protocol.cpp.
References lspserver::DidOpenTextDocumentParams::textDocument.
fromJSON() [23/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, DidSaveTextDocumentParams & R, llvm::json::Path P)
Definition at line 531 of file lspserver/src/Protocol.cpp.
References lspserver::DidSaveTextDocumentParams::textDocument.
fromJSON() [24/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, DocumentFormattingParams & R, llvm::json::Path P)
Definition at line 590 of file lspserver/src/Protocol.cpp.
References lspserver::DocumentFormattingParams::textDocument.
fromJSON() [25/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, DocumentLinkParams & R, llvm::json::Path P)
Definition at line 1464 of file lspserver/src/Protocol.cpp.
References lspserver::DocumentLinkParams::textDocument.
fromJSON() [26/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, DocumentOnTypeFormattingParams & R, llvm::json::Path P)
Definition at line 583 of file lspserver/src/Protocol.cpp.
References lspserver::DocumentOnTypeFormattingParams::ch, lspserver::DocumentOnTypeFormattingParams::position, and lspserver::DocumentOnTypeFormattingParams::textDocument.
fromJSON() [27/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, DocumentRangeFormattingParams & R, llvm::json::Path P)
Definition at line 577 of file lspserver/src/Protocol.cpp.
References lspserver::DocumentRangeFormattingParams::range, and lspserver::DocumentRangeFormattingParams::textDocument.
fromJSON() [28/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, DocumentSymbolParams & R, llvm::json::Path P)
Definition at line 596 of file lspserver/src/Protocol.cpp.
References lspserver::DocumentSymbolParams::textDocument.
fromJSON() [29/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, ExecuteCommandParams & R, llvm::json::Path P)
Definition at line 711 of file lspserver/src/Protocol.cpp.
References lspserver::ExecuteCommandParams::argument, and lspserver::ExecuteCommandParams::command.
fromJSON() [30/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, FileEvent & R, llvm::json::Path P)
Definition at line 558 of file lspserver/src/Protocol.cpp.
References lspserver::FileEvent::type, and lspserver::FileEvent::uri.
fromJSON() [31/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, FoldingRangeParams & R, llvm::json::Path P)
Definition at line 1477 of file lspserver/src/Protocol.cpp.
References lspserver::FoldingRangeParams::textDocument.
fromJSON() [32/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, InitializationOptions & Opts, llvm::json::Path P)
Definition at line 1217 of file lspserver/src/Protocol.cpp.
References lspserver::InitializationOptions::compilationDatabasePath, lspserver::InitializationOptions::ConfigSettings, lspserver::InitializationOptions::fallbackFlags, lspserver::InitializationOptions::FileStatus, and fromJSON().
fromJSON() [33/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, InitializeParams & R, llvm::json::Path P)
Definition at line 455 of file lspserver/src/Protocol.cpp.
References lspserver::InitializeParams::capabilities, lspserver::InitializeParams::initializationOptions, lspserver::InitializeParams::processId, lspserver::InitializeParams::rawCapabilities, lspserver::InitializeParams::rootPath, lspserver::InitializeParams::rootUri, and lspserver::InitializeParams::trace.
fromJSON() [34/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, InlayHintsParams & R, llvm::json::Path P)
Definition at line 1367 of file lspserver/src/Protocol.cpp.
References lspserver::InlayHintsParams::range, and lspserver::InlayHintsParams::textDocument.
fromJSON() [35/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, Location & R, llvm::json::Path P)
Definition at line 158 of file lspserver/src/Protocol.cpp.
References lspserver::Location::range, and lspserver::Location::uri.
fromJSON() [36/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, MarkupContent & R, llvm::json::Path P)
Definition at line 925 of file lspserver/src/Protocol.cpp.
References lspserver::MarkupContent::kind, and lspserver::MarkupContent::value.
fromJSON() [37/68]
bool lspserver::fromJSON (const llvm::json::Value & V, MarkupKind & K, llvm::json::Path P)
Definition at line 894 of file lspserver/src/Protocol.cpp.
References Markdown, and PlainText.
fromJSON() [38/68]
bool lspserver::fromJSON (const llvm::json::Value & , NoParams & , llvm::json::Path) inline
Definition at line 300 of file lspserver/include/lspserver/Protocol.h.
fromJSON() [39/68]
bool lspserver::fromJSON (const llvm::json::Value & V, OffsetEncoding & OE, llvm::json::Path P)
Definition at line 1433 of file lspserver/src/Protocol.cpp.
References UnsupportedEncoding, UTF16, UTF32, and UTF8.
fromJSON() [40/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, Position & R, llvm::json::Path P)
Definition at line 118 of file lspserver/src/Protocol.cpp.
References lspserver::Position::character, and lspserver::Position::line.
fromJSON() [41/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, Range & R, llvm::json::Path P)
Definition at line 135 of file lspserver/src/Protocol.cpp.
References lspserver::Range::end, and lspserver::Range::start.
fromJSON() [42/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, ReferenceParams & R, llvm::json::Path P)
Definition at line 1308 of file lspserver/src/Protocol.cpp.
References lspserver::ReferenceParams::context, and fromJSON().
fromJSON() [43/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, RenameParams & R, llvm::json::Path P)
Definition at line 1102 of file lspserver/src/Protocol.cpp.
References lspserver::RenameParams::newName, lspserver::RenameParams::position, and lspserver::RenameParams::textDocument.
fromJSON() [44/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, ResolveTypeHierarchyItemParams & R, llvm::json::Path P)
Definition at line 1294 of file lspserver/src/Protocol.cpp.
References lspserver::ResolveTypeHierarchyItemParams::direction, lspserver::ResolveTypeHierarchyItemParams::item, and lspserver::ResolveTypeHierarchyItemParams::resolve.
fromJSON() [45/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, SelectionRangeParams & S, llvm::json::Path P)
Definition at line 1449 of file lspserver/src/Protocol.cpp.
References lspserver::SelectionRangeParams::positions, and lspserver::SelectionRangeParams::textDocument.
fromJSON() [46/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, SemanticTokensParams & R, llvm::json::Path P)
Definition at line 1166 of file lspserver/src/Protocol.cpp.
References lspserver::SemanticTokensParams::textDocument.
fromJSON() [47/68]
bool lspserver::fromJSON (const llvm::json::Value & E, SymbolKind & Out, llvm::json::Path P)
Definition at line 259 of file lspserver/src/Protocol.cpp.
References File, and TypeParameter.
fromJSON() [48/68]
bool lspserver::fromJSON (const llvm::json::Value & E, SymbolKindBitset & Out, llvm::json::Path P)
Definition at line 270 of file lspserver/src/Protocol.cpp.
References fromJSON().
fromJSON() [49/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, TextDocumentContentChangeEvent & R, llvm::json::Path P)
Definition at line 570 of file lspserver/src/Protocol.cpp.
References lspserver::TextDocumentContentChangeEvent::range, lspserver::TextDocumentContentChangeEvent::rangeLength, and lspserver::TextDocumentContentChangeEvent::text.
fromJSON() [50/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, TextDocumentEdit & R, llvm::json::Path P)
Definition at line 224 of file lspserver/src/Protocol.cpp.
References lspserver::TextDocumentEdit::edits, and lspserver::TextDocumentEdit::textDocument.
fromJSON() [51/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, TextDocumentIdentifier & R, llvm::json::Path P)
Definition at line 99 of file lspserver/src/Protocol.cpp.
References lspserver::TextDocumentIdentifier::uri.
fromJSON() [52/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, TextDocumentItem & R, llvm::json::Path P)
Definition at line 184 of file lspserver/src/Protocol.cpp.
References lspserver::TextDocumentItem::languageId, lspserver::TextDocumentItem::text, lspserver::TextDocumentItem::uri, and lspserver::TextDocumentItem::version.
fromJSON() [53/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, TextDocumentPositionParams & R, llvm::json::Path P)
Definition at line 848 of file lspserver/src/Protocol.cpp.
References lspserver::TextDocumentPositionParams::position, and lspserver::TextDocumentPositionParams::textDocument.
fromJSON() [54/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, TextEdit & R, llvm::json::Path P)
Definition at line 191 of file lspserver/src/Protocol.cpp.
References lspserver::TextEdit::annotationId, lspserver::TextEdit::newText, and lspserver::TextEdit::range.
fromJSON() [55/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, TweakArgs & A, llvm::json::Path P)
Definition at line 825 of file lspserver/src/Protocol.cpp.
References lspserver::TweakArgs::file, lspserver::TweakArgs::selection, and lspserver::TweakArgs::tweakID.
fromJSON() [56/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, TypeHierarchyItem & I, llvm::json::Path P)
Definition at line 1279 of file lspserver/src/Protocol.cpp.
References lspserver::TypeHierarchyItem::children, lspserver::TypeHierarchyItem::data, lspserver::TypeHierarchyItem::deprecated, lspserver::TypeHierarchyItem::detail, lspserver::TypeHierarchyItem::kind, lspserver::TypeHierarchyItem::name, lspserver::TypeHierarchyItem::parents, lspserver::TypeHierarchyItem::range, lspserver::TypeHierarchyItem::selectionRange, and lspserver::TypeHierarchyItem::uri.
fromJSON() [57/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, TypeHierarchyPrepareParams & R, llvm::json::Path P)
Definition at line 1241 of file lspserver/src/Protocol.cpp.
References lspserver::TypeHierarchyPrepareParams::direction, lspserver::TextDocumentPositionParams::position, lspserver::TypeHierarchyPrepareParams::resolve, and lspserver::TextDocumentPositionParams::textDocument.
fromJSON() [58/68]
bool lspserver::fromJSON (const llvm::json::Value & E, URIForFile & R, llvm::json::Path P)
Definition at line 64 of file lspserver/src/Protocol.cpp.
References lspserver::URIForFile::fromURI(), and lspserver::URI::parse().
Referenced by fromJSON(), fromJSON(), fromJSON(), fromJSON(), fromJSON(), fromJSON(), fromJSON(), and parseParam().
fromJSON() [59/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, VersionedTextDocumentIdentifier & R, llvm::json::Path P)
Definition at line 111 of file lspserver/src/Protocol.cpp.
References fromJSON(), and lspserver::VersionedTextDocumentIdentifier::version.
fromJSON() [60/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, WorkspaceEdit & R, llvm::json::Path P)
Definition at line 703 of file lspserver/src/Protocol.cpp.
References lspserver::WorkspaceEdit::changeAnnotations, lspserver::WorkspaceEdit::changes, and lspserver::WorkspaceEdit::documentChanges.
fromJSON() [61/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, WorkspaceSymbolParams & R, llvm::json::Path P)
Definition at line 753 of file lspserver/src/Protocol.cpp.
References lspserver::WorkspaceSymbolParams::limit, and lspserver::WorkspaceSymbolParams::query.
fromJSON() [62/68]
bool lspserver::fromJSON (const llvm::json::Value & E, FileChangeType & Out, llvm::json::Path P)
Definition at line 546 of file lspserver/src/Protocol.cpp.
References Created, and Deleted.
fromJSON() [63/68]
bool lspserver::fromJSON (const llvm::json::Value & E, TraceLevel & Out, llvm::json::Path P)
Definition at line 241 of file lspserver/src/Protocol.cpp.
References Messages, Off, and Verbose.
fromJSON() [64/68]
bool lspserver::fromJSON (const llvm::json::Value & E, TypeHierarchyDirection & Out, llvm::json::Path P)
Definition at line 1229 of file lspserver/src/Protocol.cpp.
References Both, and Children.
fromJSON() [65/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, ReferenceContext & R, llvm::json::Path P)
Definition at line 1302 of file lspserver/src/Protocol.cpp.
References lspserver::ReferenceContext::includeDeclaration.
fromJSON() [66/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, SemanticTokensDeltaParams & R, llvm::json::Path P)
Definition at line 1172 of file lspserver/src/Protocol.cpp.
References lspserver::SemanticTokensDeltaParams::previousResultId, and lspserver::SemanticTokensDeltaParams::textDocument.
fromJSON() [67/68]
bool lspserver::fromJSON (const llvm::json::Value & Params, TypeHierarchyItem::ResolveParams & RP, llvm::json::Path P)
Definition at line 1261 of file lspserver/src/Protocol.cpp.
References lspserver::TypeHierarchyItem::ResolveParams::parents.
fromJSON() [68/68]
bool lspserver::fromJSON (const TypeHierarchyItem::ResolveParams &)
log()
template<typename... Ts> void lspserver::log (const char * Fmt, Ts &&... Vals)
Definition at line 58 of file Logger.h.
References lspserver::Logger::Info, and lspserver::detail::log().
Referenced by lspserver::LSPServer::mkOutNotifiction(), and nixd::EvalClient::onReady().
lspLength()
size_t lspserver::lspLength (llvm::StringRef Code)
Definition at line 51 of file SourceCode.cpp.
References UnsupportedEncoding, UTF16, UTF32, and UTF8.
Referenced by applyChange(), and offsetToPosition().
maybeCaseFoldPath()
std::string lspserver::maybeCaseFoldPath (PathRef Path)
offsetToPosition()
Position lspserver::offsetToPosition (llvm::StringRef Code, size_t Offset)
Turn an offset in Code into a [line, column] pair. The offset must be in range [0, Code.size()].
Definition at line 145 of file SourceCode.cpp.
References lspserver::Position::character, lspserver::Position::line, and lspLength().
Referenced by nixd::toLSPPosition().
operator<() [1/2]
bool lspserver::operator< (const CompletionItem & L, const CompletionItem & R)
Definition at line 1047 of file lspserver/src/Protocol.cpp.
References lspserver::CompletionItem::label, and lspserver::CompletionItem::sortText.
operator<() [2/2]
bool lspserver::operator< (const InlayHint & A, const InlayHint & B)
Definition at line 1399 of file lspserver/src/Protocol.cpp.
References lspserver::InlayHint::kind, lspserver::InlayHint::label, lspserver::InlayHint::position, and lspserver::InlayHint::range.
operator<<() [1/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & OS, const ASTNode & Root)
Definition at line 1523 of file lspserver/src/Protocol.cpp.
References lspserver::ASTNode::children, lspserver::ASTNode::detail, lspserver::ASTNode::kind, and lspserver::ASTNode::role.
operator<<() [2/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & O, const CompletionItem & I)
Definition at line 1042 of file lspserver/src/Protocol.cpp.
References lspserver::CompletionItem::label, and toJSON().
operator<<() [3/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & OS, const Diagnostic & D)
Definition at line 674 of file lspserver/src/Protocol.cpp.
References lspserver::Diagnostic::message, lspserver::Diagnostic::range, and lspserver::Diagnostic::severity.
operator<<() [4/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & O, const DocumentHighlight & V)
Definition at line 1185 of file lspserver/src/Protocol.cpp.
References lspserver::DocumentHighlight::kind, lspserver::DocumentHighlight::range, Read, and Write.
operator<<() [5/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & OS, const Location & L)
Definition at line 164 of file lspserver/src/Protocol.cpp.
References lspserver::Location::range, and lspserver::Location::uri.
operator<<() [6/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & OS, const Position & P)
Definition at line 131 of file lspserver/src/Protocol.cpp.
References lspserver::Position::character, and lspserver::Position::line.
operator<<() [7/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & OS, const Range & R)
Definition at line 147 of file lspserver/src/Protocol.cpp.
References lspserver::Range::end, and lspserver::Range::start.
operator<<() [8/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & OS, const ReferenceLocation & L)
Definition at line 178 of file lspserver/src/Protocol.cpp.
References lspserver::ReferenceLocation::containerName, lspserver::Location::range, and lspserver::Location::uri.
operator<<() [9/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & O, const SignatureInformation & I)
Definition at line 1084 of file lspserver/src/Protocol.cpp.
References lspserver::SignatureInformation::label, and toJSON().
operator<<() [10/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & O, const SymbolInformation & SI)
Definition at line 747 of file lspserver/src/Protocol.cpp.
References lspserver::SymbolInformation::containerName, lspserver::SymbolInformation::name, and toJSON().
operator<<() [11/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & OS, const TextEdit & TE)
Definition at line 235 of file lspserver/src/Protocol.cpp.
References lspserver::TextEdit::newText, and lspserver::TextEdit::range.
operator<<() [12/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & O, const TypeHierarchyItem & I)
Definition at line 1250 of file lspserver/src/Protocol.cpp.
References lspserver::TypeHierarchyItem::name, and toJSON().
operator<<() [13/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & OS, InlayHintKind Kind)
Definition at line 1404 of file lspserver/src/Protocol.cpp.
References Designator, Parameter, and Type.
operator<<() [14/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & OS, OffsetEncoding Enc)
Definition at line 1445 of file lspserver/src/Protocol.cpp.
operator<<() [15/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & O, const DocumentSymbol & S)
Definition at line 786 of file lspserver/src/Protocol.cpp.
References lspserver::DocumentSymbol::name, and toJSON().
operator<<() [16/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & OS, const URIForFile & U)
Definition at line 91 of file lspserver/src/Protocol.cpp.
References lspserver::URIForFile::uri().
operator<<() [17/17]
llvm::raw_ostream & lspserver::operator<< (llvm::raw_ostream & OS, MarkupKind K)
Definition at line 911 of file lspserver/src/Protocol.cpp.
operator==() [1/3]
bool lspserver::operator== (const InlayHint & A, const InlayHint & B)
Definition at line 1395 of file lspserver/src/Protocol.cpp.
References lspserver::InlayHint::kind, lspserver::InlayHint::label, lspserver::InlayHint::position, and lspserver::InlayHint::range.
operator==() [2/3]
bool lspserver::operator== (const SemanticToken & L, const SemanticToken & R)
Definition at line 1138 of file lspserver/src/Protocol.cpp.
References lspserver::SemanticToken::deltaLine, lspserver::SemanticToken::deltaStart, lspserver::SemanticToken::length, lspserver::SemanticToken::tokenModifiers, and lspserver::SemanticToken::tokenType.
operator==() [3/3]
bool lspserver::operator== (const TextEdit & L, const TextEdit & R) inline
Definition at line 238 of file lspserver/include/lspserver/Protocol.h.
References lspserver::TextEdit::annotationId, lspserver::TextEdit::newText, and lspserver::TextEdit::range.
parseParam() [1/2]
template<typename T> llvm::Expected< T > lspserver::parseParam (const llvm::json::Value & Raw, llvm::StringRef PayloadName, llvm::StringRef PayloadKind)
Definition at line 13 of file LSPBinder.h.
References elog(), fromJSON(), InvalidParams, and vlog().
Referenced by lspserver::HandlerRegistry::addCommand(), lspserver::HandlerRegistry::addMethod(), lspserver::HandlerRegistry::addNotification(), and lspserver::LSPServer::mkOutMethod().
parseParam() [2/2]
template<> llvm::Expected< llvm::json::Value > lspserver::parseParam (const llvm::json::Value & Raw, llvm::StringRef PayloadName, llvm::StringRef PayloadKind) inline
Definition at line 37 of file LSPBinder.h.
pathEqual()
bool lspserver::pathEqual (PathRef , PathRef)
pathStartsWith()
bool lspserver::pathStartsWith (PathRef Ancestor, PathRef Path, llvm::sys::path::Style Style = llvm::sys::path::Style::native)
Checks if Ancestor is a proper ancestor of Path. This is just a smarter lexical prefix match, e.g: foo/bar/baz doesn't start with foo/./bar. Both Ancestor and Path must be absolute.
positionToOffset()
llvm::Expected< size_t > lspserver::positionToOffset (llvm::StringRef Code, Position P, bool AllowColumnsBeyondLineLength = true)
Turn a [line, column] pair into an offset in Code.
If P.character exceeds the line length, returns the offset at end-of-line. (If !AllowColumnsBeyondLineLength, then returns an error instead). If the line number is out of range, returns an error.
The returned value is in the range [0, Code.size()].
Definition at line 116 of file SourceCode.cpp.
References lspserver::Position::character, error(), and lspserver::Position::line.
Referenced by applyChange().
readLine()
bool lspserver::readLine (int fd, const std::atomic< bool > & Close, llvm::SmallString< 128 > & Line)
Definition at line 163 of file Connection.cpp.
Referenced by lspserver::InboundPort::readLitTestMessage(), and lspserver::InboundPort::readStandardMessage().
toJSON() [1/58]
llvm::json::Value lspserver::toJSON (const ApplyWorkspaceEditParams & Params)
Definition at line 837 of file lspserver/src/Protocol.cpp.
References lspserver::ApplyWorkspaceEditParams::edit.
toJSON() [2/58]
llvm::json::Value lspserver::toJSON (const ASTNode & N)
Definition at line 1507 of file lspserver/src/Protocol.cpp.
References lspserver::ASTNode::arcana, lspserver::ASTNode::children, lspserver::ASTNode::detail, lspserver::ASTNode::kind, lspserver::ASTNode::range, and lspserver::ASTNode::role.
toJSON() [3/58]
llvm::json::Value lspserver::toJSON (const CallHierarchyIncomingCall & C)
Definition at line 1353 of file lspserver/src/Protocol.cpp.
References lspserver::CallHierarchyIncomingCall::from, and lspserver::CallHierarchyIncomingCall::fromRanges.
toJSON() [4/58]
llvm::json::Value lspserver::toJSON (const CallHierarchyItem & I)
Definition at line 1319 of file lspserver/src/Protocol.cpp.
References lspserver::CallHierarchyItem::data, lspserver::CallHierarchyItem::detail, lspserver::CallHierarchyItem::kind, lspserver::CallHierarchyItem::name, lspserver::CallHierarchyItem::range, lspserver::CallHierarchyItem::selectionRange, lspserver::CallHierarchyItem::tags, and lspserver::CallHierarchyItem::uri.
toJSON() [5/58]
llvm::json::Value lspserver::toJSON (const CallHierarchyOutgoingCall & C)
Definition at line 1363 of file lspserver/src/Protocol.cpp.
References lspserver::CallHierarchyOutgoingCall::fromRanges, and lspserver::CallHierarchyOutgoingCall::to.
toJSON() [6/58]
llvm::json::Value lspserver::toJSON (const ChangeAnnotation & CA)
Definition at line 215 of file lspserver/src/Protocol.cpp.
References lspserver::ChangeAnnotation::description, lspserver::ChangeAnnotation::label, and lspserver::ChangeAnnotation::needsConfirmation.
toJSON() [7/58]
llvm::json::Value lspserver::toJSON (const CodeAction & CA)
Definition at line 771 of file lspserver/src/Protocol.cpp.
References lspserver::CodeAction::command, lspserver::CodeAction::diagnostics, lspserver::CodeAction::edit, lspserver::CodeAction::isPreferred, lspserver::CodeAction::kind, and lspserver::CodeAction::title.
toJSON() [8/58]
llvm::json::Value lspserver::toJSON (const CodeDescription & D)
Definition at line 611 of file lspserver/src/Protocol.cpp.
References lspserver::CodeDescription::href.
toJSON() [9/58]
llvm::json::Value lspserver::toJSON (const Command & C)
Definition at line 760 of file lspserver/src/Protocol.cpp.
References lspserver::ExecuteCommandParams::argument, lspserver::ExecuteCommandParams::command, and lspserver::Command::title.
toJSON() [10/58]
llvm::json::Value lspserver::toJSON (const CompletionItem & CI)
Definition at line 990 of file lspserver/src/Protocol.cpp.
References lspserver::CompletionItem::additionalTextEdits, lspserver::CompletionItem::data, lspserver::CompletionItem::deprecated, lspserver::CompletionItem::detail, lspserver::CompletionItem::documentation, lspserver::CompletionItem::filterText, lspserver::CompletionItem::insertText, lspserver::CompletionItem::insertTextFormat, lspserver::CompletionItem::kind, lspserver::CompletionItem::label, Missing, lspserver::CompletionItem::score, lspserver::CompletionItem::sortText, and lspserver::CompletionItem::textEdit.
toJSON() [11/58]
llvm::json::Value lspserver::toJSON (const CompletionList & L)
Definition at line 1052 of file lspserver/src/Protocol.cpp.
References lspserver::CompletionList::isIncomplete, and lspserver::CompletionList::items.
toJSON() [12/58]
llvm::json::Value lspserver::toJSON (const ConfigurationItem & N)
Definition at line 1537 of file lspserver/src/Protocol.cpp.
References lspserver::ConfigurationItem::scopeUri, and lspserver::ConfigurationItem::section.
toJSON() [13/58]
llvm::json::Value lspserver::toJSON (const ConfigurationParams & N)
Definition at line 1546 of file lspserver/src/Protocol.cpp.
References lspserver::ConfigurationParams::items.
toJSON() [14/58]
llvm::json::Value lspserver::toJSON (const Diagnostic & D)
Definition at line 615 of file lspserver/src/Protocol.cpp.
References lspserver::Diagnostic::category, lspserver::Diagnostic::code, lspserver::Diagnostic::codeActions, lspserver::Diagnostic::codeDescription, lspserver::Diagnostic::data, lspserver::Diagnostic::message, lspserver::Diagnostic::range, lspserver::Diagnostic::relatedInformation, lspserver::Diagnostic::severity, lspserver::Diagnostic::source, and lspserver::Diagnostic::tags.
toJSON() [15/58]
llvm::json::Value lspserver::toJSON (const DiagnosticRelatedInformation & DRI)
Definition at line 602 of file lspserver/src/Protocol.cpp.
References lspserver::DiagnosticRelatedInformation::location, and lspserver::DiagnosticRelatedInformation::message.
toJSON() [16/58]
llvm::json::Value lspserver::toJSON (const DocumentHighlight & DH)
Definition at line 1109 of file lspserver/src/Protocol.cpp.
References lspserver::DocumentHighlight::kind, lspserver::DocumentHighlight::range, and toJSON().
toJSON() [17/58]
llvm::json::Value lspserver::toJSON (const DocumentLink & DocumentLink)
Definition at line 1470 of file lspserver/src/Protocol.cpp.
References lspserver::DocumentLink::range, and lspserver::DocumentLink::target.
toJSON() [18/58]
llvm::json::Value lspserver::toJSON (const DocumentSymbol & S)
Definition at line 790 of file lspserver/src/Protocol.cpp.
References lspserver::DocumentSymbol::children, lspserver::DocumentSymbol::deprecated, lspserver::DocumentSymbol::detail, lspserver::DocumentSymbol::kind, lspserver::DocumentSymbol::name, lspserver::DocumentSymbol::range, and lspserver::DocumentSymbol::selectionRange.
toJSON() [19/58]
llvm::json::Value lspserver::toJSON (const FileStatus & FStatus)
Definition at line 1116 of file lspserver/src/Protocol.cpp.
References lspserver::FileStatus::state, and lspserver::FileStatus::uri.
toJSON() [20/58]
llvm::json::Value lspserver::toJSON (const FoldingRange & Range)
Definition at line 1487 of file lspserver/src/Protocol.cpp.
toJSON() [21/58]
llvm::json::Value lspserver::toJSON (const Hover & H)
Definition at line 934 of file lspserver/src/Protocol.cpp.
References lspserver::Hover::contents, lspserver::Hover::range, and toJSON().
toJSON() [22/58]
llvm::json::Value lspserver::toJSON (const InactiveRegionsParams & InactiveRegions)
Definition at line 1179 of file lspserver/src/Protocol.cpp.
References lspserver::InactiveRegionsParams::InactiveRegions, and lspserver::InactiveRegionsParams::TextDocument.
toJSON() [23/58]
llvm::json::Value lspserver::toJSON (const InlayHint & H)
Definition at line 1385 of file lspserver/src/Protocol.cpp.
References lspserver::InlayHint::kind, lspserver::InlayHint::label, lspserver::InlayHint::paddingLeft, lspserver::InlayHint::paddingRight, lspserver::InlayHint::position, and toJSON().
toJSON() [24/58]
llvm::json::Value lspserver::toJSON (const InlayHintKind & Kind)
Definition at line 1373 of file lspserver/src/Protocol.cpp.
References Designator, Parameter, and Type.
toJSON() [25/58]
llvm::json::Value lspserver::toJSON (const Location & P)
Definition at line 151 of file lspserver/src/Protocol.cpp.
References lspserver::Location::range, and lspserver::Location::uri.
toJSON() [26/58]
llvm::json::Value lspserver::toJSON (const MarkupContent & MC)
Definition at line 915 of file lspserver/src/Protocol.cpp.
References lspserver::MarkupContent::kind, and lspserver::MarkupContent::value.
toJSON() [27/58]
llvm::json::Value lspserver::toJSON (const MessageType & R)
Definition at line 511 of file lspserver/src/Protocol.cpp.
toJSON() [28/58]
llvm::json::Value lspserver::toJSON (const NoParams &) inline
Definition at line 299 of file lspserver/include/lspserver/Protocol.h.
toJSON() [29/58]
llvm::json::Value lspserver::toJSON (const OffsetEncoding & OE)
Definition at line 1432 of file lspserver/src/Protocol.cpp.
toJSON() [30/58]
llvm::json::Value lspserver::toJSON (const ParameterInformation & PI)
Definition at line 1059 of file lspserver/src/Protocol.cpp.
References lspserver::ParameterInformation::documentation, lspserver::ParameterInformation::labelOffsets, and lspserver::ParameterInformation::labelString.
toJSON() [31/58]
llvm::json::Value lspserver::toJSON (const Position & P)
Definition at line 124 of file lspserver/src/Protocol.cpp.
References lspserver::Position::character, and lspserver::Position::line.
toJSON() [32/58]
template<typename T> llvm::json::Value lspserver::toJSON (const ProgressParams< T > & P)
Definition at line 632 of file lspserver/include/lspserver/Protocol.h.
References lspserver::ProgressParams< T >::token, and lspserver::ProgressParams< T >::value.
toJSON() [33/58]
llvm::json::Value lspserver::toJSON (const PublishDiagnosticsParams & PDP)
Definition at line 655 of file lspserver/src/Protocol.cpp.
References lspserver::PublishDiagnosticsParams::diagnostics, lspserver::PublishDiagnosticsParams::uri, and lspserver::PublishDiagnosticsParams::version.
toJSON() [34/58]
llvm::json::Value lspserver::toJSON (const Range & P)
Definition at line 140 of file lspserver/src/Protocol.cpp.
References lspserver::Range::end, and lspserver::Range::start.
toJSON() [35/58]
llvm::json::Value lspserver::toJSON (const ReferenceLocation & P)
Definition at line 168 of file lspserver/src/Protocol.cpp.
References lspserver::ReferenceLocation::containerName, lspserver::Location::range, and lspserver::Location::uri.
toJSON() [36/58]
llvm::json::Value lspserver::toJSON (const SelectionRange & Out)
Definition at line 1456 of file lspserver/src/Protocol.cpp.
References lspserver::SelectionRange::parent, lspserver::SelectionRange::range, and toJSON().
toJSON() [37/58]
llvm::json::Value lspserver::toJSON (const SemanticTokens & Tokens)
Definition at line 1145 of file lspserver/src/Protocol.cpp.
toJSON() [38/58]
llvm::json::Value lspserver::toJSON (const SemanticTokensEdit & Edit)
Definition at line 1150 of file lspserver/src/Protocol.cpp.
References lspserver::SemanticTokensEdit::deleteTokens, SemanticTokenEncodingSize, lspserver::SemanticTokensEdit::startToken, and lspserver::SemanticTokensEdit::tokens.
toJSON() [39/58]
llvm::json::Value lspserver::toJSON (const SemanticTokensOrDelta & TE)
Definition at line 1157 of file lspserver/src/Protocol.cpp.
References lspserver::SemanticTokensOrDelta::edits, lspserver::SemanticTokensOrDelta::resultId, and lspserver::SemanticTokensOrDelta::tokens.
toJSON() [40/58]
llvm::json::Value lspserver::toJSON (const ShowMessageParams & R)
Definition at line 515 of file lspserver/src/Protocol.cpp.
References lspserver::ShowMessageParams::message, and lspserver::ShowMessageParams::type.
toJSON() [41/58]
llvm::json::Value lspserver::toJSON (const SignatureHelp & SH)
Definition at line 1090 of file lspserver/src/Protocol.cpp.
References lspserver::SignatureHelp::activeParameter, lspserver::SignatureHelp::activeSignature, and lspserver::SignatureHelp::signatures.
toJSON() [42/58]
llvm::json::Value lspserver::toJSON (const SignatureInformation & SI)
Definition at line 1073 of file lspserver/src/Protocol.cpp.
References lspserver::SignatureInformation::documentation, lspserver::SignatureInformation::label, lspserver::SignatureInformation::parameters, and lspserver::MarkupContent::value.
toJSON() [43/58]
llvm::json::Value lspserver::toJSON (const SymbolInformation & P)
Definition at line 735 of file lspserver/src/Protocol.cpp.
References lspserver::SymbolInformation::containerName, lspserver::SymbolInformation::kind, lspserver::SymbolInformation::location, lspserver::SymbolInformation::name, and lspserver::SymbolInformation::score.
toJSON() [44/58]
llvm::json::Value lspserver::toJSON (const TextDocumentEdit & P)
Definition at line 229 of file lspserver/src/Protocol.cpp.
References lspserver::TextDocumentEdit::edits, and lspserver::TextDocumentEdit::textDocument.
toJSON() [45/58]
llvm::json::Value lspserver::toJSON (const TextDocumentIdentifier & R)
Definition at line 95 of file lspserver/src/Protocol.cpp.
References lspserver::TextDocumentIdentifier::uri.
toJSON() [46/58]
llvm::json::Value lspserver::toJSON (const TextEdit & P)
Definition at line 198 of file lspserver/src/Protocol.cpp.
References lspserver::TextEdit::annotationId, lspserver::TextEdit::newText, and lspserver::TextEdit::range.
toJSON() [47/58]
llvm::json::Value lspserver::toJSON (const TweakArgs & A)
Definition at line 832 of file lspserver/src/Protocol.cpp.
References lspserver::TweakArgs::file, lspserver::TweakArgs::selection, and lspserver::TweakArgs::tweakID.
toJSON() [48/58]
llvm::json::Value lspserver::toJSON (const TypeHierarchyItem & I)
Definition at line 1267 of file lspserver/src/Protocol.cpp.
References lspserver::TypeHierarchyItem::data, lspserver::TypeHierarchyItem::detail, lspserver::TypeHierarchyItem::kind, lspserver::TypeHierarchyItem::name, lspserver::TypeHierarchyItem::range, lspserver::TypeHierarchyItem::selectionRange, and lspserver::TypeHierarchyItem::uri.
toJSON() [49/58]
llvm::json::Value lspserver::toJSON (const TypeHierarchyItem::ResolveParams & RP)
Definition at line 1255 of file lspserver/src/Protocol.cpp.
References lspserver::TypeHierarchyItem::ResolveParams::parents.
toJSON() [50/58]
llvm::json::Value lspserver::toJSON (const URIForFile & U)
Serialize/deserialize URIForFile to/from a string URI.
Definition at line 89 of file lspserver/src/Protocol.cpp.
References lspserver::URIForFile::uri().
Referenced by operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), toJSON(), toJSON(), toJSON(), toJSON(), and toJSON().
toJSON() [51/58]
llvm::json::Value lspserver::toJSON (const VersionedTextDocumentIdentifier & R)
Definition at line 105 of file lspserver/src/Protocol.cpp.
References toJSON(), and lspserver::VersionedTextDocumentIdentifier::version.
toJSON() [52/58]
llvm::json::Value lspserver::toJSON (const WorkDoneProgressBegin & P)
Definition at line 477 of file lspserver/src/Protocol.cpp.
References lspserver::WorkDoneProgressBegin::cancellable, lspserver::WorkDoneProgressBegin::percentage, and lspserver::WorkDoneProgressBegin::title.
toJSON() [53/58]
llvm::json::Value lspserver::toJSON (const WorkDoneProgressCreateParams & P)
Definition at line 473 of file lspserver/src/Protocol.cpp.
References lspserver::WorkDoneProgressCreateParams::token.
toJSON() [54/58]
llvm::json::Value lspserver::toJSON (const WorkDoneProgressEnd & P)
Definition at line 503 of file lspserver/src/Protocol.cpp.
References lspserver::WorkDoneProgressEnd::message.
toJSON() [55/58]
llvm::json::Value lspserver::toJSON (const WorkDoneProgressReport & P)
Definition at line 491 of file lspserver/src/Protocol.cpp.
References lspserver::WorkDoneProgressReport::cancellable, lspserver::WorkDoneProgressReport::message, and lspserver::WorkDoneProgressReport::percentage.
toJSON() [56/58]
llvm::json::Value lspserver::toJSON (const WorkspaceEdit & WE)
Definition at line 806 of file lspserver/src/Protocol.cpp.
References lspserver::WorkspaceEdit::changeAnnotations, lspserver::WorkspaceEdit::changes, and lspserver::WorkspaceEdit::documentChanges.
toJSON() [57/58]
llvm::json::Value lspserver::toJSON (DiagnosticTag Tag)
Definition at line 609 of file lspserver/src/Protocol.cpp.
toJSON() [58/58]
llvm::json::Value lspserver::toJSON (SymbolTag Tag)
Definition at line 1315 of file lspserver/src/Protocol.cpp.
unionRanges()
void lspserver::unionRanges (Range & A, Range B)
vlog()
template<typename... Ts> void lspserver::vlog (const char * Fmt, Ts &&... Vals)
Definition at line 63 of file Logger.h.
References lspserver::detail::log(), and lspserver::Logger::Verbose.
Referenced by lspserver::InboundPort::loop(), parseParam(), and lspserver::OutboundPort::sendMessage().
Variable Documentation
CompletionItemKindMax
auto lspserver::CompletionItemKindMax constexpr
Initial value:
=
    static_cast<size_t>(CompletionItemKind::TypeParameter)
Definition at line 352 of file lspserver/include/lspserver/Protocol.h.
CompletionItemKindMin
auto lspserver::CompletionItemKindMin constexpr
Initial value:
=
    static_cast<size_t>(CompletionItemKind::Text)
Definition at line 350 of file lspserver/include/lspserver/Protocol.h.
Referenced by adjustKindToCapability().
kCurrentOffsetEncoding
Key<OffsetEncoding> lspserver::kCurrentOffsetEncoding extern
SemanticTokenEncodingSize
unsigned lspserver::SemanticTokenEncodingSize = 5 constexpr
Definition at line 1123 of file lspserver/src/Protocol.cpp.
Referenced by toJSON().
SymbolKindMax
auto lspserver::SymbolKindMax = static_cast<size_t>(SymbolKind::TypeParameter) constexpr
Definition at line 392 of file lspserver/include/lspserver/Protocol.h.
SymbolKindMin
auto lspserver::SymbolKindMin = static_cast<size_t>(SymbolKind::File) constexpr
Definition at line 391 of file lspserver/include/lspserver/Protocol.h.
Referenced by adjustKindToCapability().