nixd: nixf::tok Namespace Reference
nixf::tok Namespace Reference
Enumerations
enum TokenKind
Functions
constexpr std::string_view spelling (TokenKind Kind)
Enumeration Type Documentation
TokenKind
enum nixf::tok::TokenKind
Definition at line 5 of file TokenKinds.h.
Function Documentation
spelling()
constexpr std::string_view nixf::tok::spelling (TokenKind Kind) constexpr
Definition at line 13 of file Token.h.
Referenced by nixf::Parser::parseBinding(), nixf::Parser::parseExprAssert(), nixf::Parser::parseExprAttrs(), nixf::Parser::parseExprIf(), nixf::Parser::parseExprList(), nixf::Parser::parseExprParen(), nixf::Parser::parseExprWith(), nixf::Parser::parseFormals(), nixf::Parser::parseInherit(), nixf::Parser::parseInterpolation(), nixf::Parser::parseLambdaArg(), and nixf::Parser::parseString().