nixd: nixf::detail Namespace Reference
nixf::detail Namespace Reference
Functions
Diagnostic & diagNullExpr (std::vector< Diagnostic > &Diags, LexerCursor Loc, std::string As)
Function Documentation
diagNullExpr()
Diagnostic & nixf::detail::diagNullExpr (std::vector< Diagnostic > & Diags, LexerCursor Loc, std::string As)
Definition at line 11 of file ParseSupport.cpp.
References nixf::Fix::edit(), nixf::Diagnostic::fix(), and nixf::TextEdit::mkInsertion().
Referenced by nixf::Parser::parseBinding(), nixf::Parser::parseExprAssert(), nixf::Parser::parseExprIf(), nixf::Parser::parseExprLambda(), nixf::Parser::parseExprLet(), nixf::Parser::parseExprParen(), nixf::Parser::parseExprSelect(), nixf::Parser::parseExprWith(), nixf::Parser::parseFormal(), nixf::Parser::parseInherit(), and nixf::Parser::parseInterpolation().