nixd: TokenKinds Namespace Reference
TokenKinds Namespace Reference
Functions
str generate_token_section (str section_name, list tokens)
str generate_token_kinds_inc ()
Function Documentation
generate_token_kinds_inc()
str TokenKinds.generate_token_kinds_inc ()
Definition at line 15 of file TokenKinds.inc.py.
References generate_token_kinds_inc(), and generate_token_section().
Referenced by generate_token_kinds_inc().
generate_token_section()
str TokenKinds.generate_token_section (str section_name, list tokens)
Definition at line 4 of file TokenKinds.inc.py.
Referenced by generate_token_kinds_inc().