nixd: bc Namespace Reference
bc Namespace Reference
Functions
template<class T >
void readBytecode (std::string_view &Data, T &Obj)
template<class T >
requires std::is_standard_layout_v<T> && std::is_trivial_v<T>
void readBytecode (std::string_view &Data, T &Obj)
Basic primitives. Deocde from bytes by memcpy.
template<class T >
void readBytecode (std::string_view &Data, std::vector< T > &Obj)
template<>
void readBytecode< std::string > (std::string_view &Data, std::string &Obj)
template<class T >
T eat (std::string_view &Data)
template<class T >
requires std::is_standard_layout_v<T> && std::is_trivial_v<T>
void writeBytecode (std::ostream &OS, const T &Data)
Basic primitives. Trivial data types are just written to a stream.
void writeBytecode (std::ostream &OS, const std::string_view &Data)
void writeBytecode (std::ostream &OS, const std::string &Data)
template<class T >
std::string toBytecode (const T &Data)
template<>
void readBytecode< std::string > (std::string_view &Data, std::string &Obj)
Function Documentation
eat()
template<class T > T bc::eat (std::string_view & Data)
Definition at line 38 of file Read.h.
References readBytecode().
readBytecode() [1/3]
template<class T > void bc::readBytecode (std::string_view & Data, std::vector< T > & Obj)
Definition at line 27 of file Read.h.
References readBytecode().
readBytecode() [2/3]
template<class T > void bc::readBytecode (std::string_view & Data, T & Obj)
Definition at line 12 of file Read.h.
Referenced by eat(), readBytecode(), and readBytecode< std::string >().
readBytecode() [3/3]
template<class T > requires std::is_standard_layout_v<T> && std::is_trivial_v<T> void bc::readBytecode (std::string_view & Data, T & Obj)
Basic primitives. Deocde from bytes by memcpy.
Definition at line 20 of file Read.h.
readBytecode< std::string >() [1/2]
template<> void bc::readBytecode< std::string > (std::string_view & Data, std::string & Obj)
Definition at line 6 of file Read.cpp.
References readBytecode().
readBytecode< std::string >() [2/2]
template<> void bc::readBytecode< std::string > (std::string_view & Data, std::string & Obj)
Definition at line 6 of file Read.cpp.
References readBytecode().
toBytecode()
template<class T > std::string bc::toBytecode (const T & Data)
Definition at line 22 of file libbc/include/bc/Write.h.
References writeBytecode().
writeBytecode() [1/3]
void bc::writeBytecode (std::ostream & OS, const std::string & Data) inline
Definition at line 18 of file libbc/include/bc/Write.h.
References writeBytecode().
writeBytecode() [2/3]
void bc::writeBytecode (std::ostream & OS, const std::string_view & Data)
Definition at line 5 of file libbc/src/Write.cpp.
References writeBytecode().
writeBytecode() [3/3]
template<class T > requires std::is_standard_layout_v<T> && std::is_trivial_v<T> void bc::writeBytecode (std::ostream & OS, const T & Data)
Basic primitives. Trivial data types are just written to a stream.
Definition at line 12 of file libbc/include/bc/Write.h.
Referenced by toBytecode(), writeBytecode(), and writeBytecode().