nixd: nixf-tidy.cpp File Reference
nixf-tidy.cpp File Reference
nixf-tidy, provide linting based on libnixf.
#include "nixf/Basic/JSONDiagnostic.h"
#include "nixf/Basic/Nodes/Basic.h"
#include "nixf/Parse/Parser.h"
#include "nixf/Sema/VariableLookup.h"
#include <iostream>
#include <sstream>
Functions
int main (int Argc, const char *Argv[])
Detailed Description
nixf-tidy, provide linting based on libnixf.
Definition in file nixf-tidy.cpp.
Function Documentation
main()
int main (int Argc, const char * Argv[])
Definition at line 33 of file nixf-tidy.cpp.
References nixf::parse(), nixf::VariableLookupAnalysis::runOnAST(), and nixf::to_json().