test(
    'unit/nixd/configuration',
    executable(
        'unit-nixd-configuration',
        'Configuration.cpp',
        'EditorConfig.cpp',
        'FormatterLifecycle.cpp',
        'ProviderRegistry.cpp',
        'Startup.cpp',
        'TransportLifecycle.cpp',
        dependencies: [ libnixd, gtest_main ],
    ),
)
